### ISSUE TITLE
BT Pair Fails 

### ISSUE THREAD

**Issue by maheshtalewad** [bluez/bluez#1014]
![image](https://github.com/user-attachments/assets/7f35ec09-7928-4161-8a78-b3a78eed45b0)
[dmesg_fail_5.txt](https://github.com/user-attachments/files/17697873/dmesg_fail_5.txt)
[fail_btmon.txt](https://github.com/user-attachments/files/17697883/fail_btmon.txt)

**Comment by maheshtalewad** [comment]
Below commit is causing this issue:
https://patches.linaro.org/project/linux-bluetooth/patch/20240923165116.1540227-1-luiz.dentz@gmail.com/
+       if (conn && hci_dev_test_flag(hdev, HCI_MGMT))
+               mgmt_device_connected(hdev, conn, NULL, 0)

**Comment by Vudentz** [comment]
@maheshtalewad please check if https://patchwork.kernel.org/project/bluetooth/patch/20241108162608.262188-1-luiz.dentz@gmail.com/ fixes it.

**Comment by maheshtalewad** [comment]
> @maheshtalewad please check if https://patchwork.kernel.org/project/bluetooth/patch/20241108162608.262188-1-luiz.dentz@gmail.com/ fixes it.

Hi Luiz,
This patch fixed the issue.

Thanks and regards,
Mahesh Vithal Talewad

**Comment by joakim-tjernlund** [comment]
Should this fix be in kernel 6.6.x too? It is not ATM
