### ISSUE TITLE
Post S5 the next iteration of remote wake from connected standby fails

### ISSUE THREAD

**Issue by devegowdIntel** [bluez/bluez#1028]
Test steps:
1. Connect LE mouse
2. Put the DUT to connected standby  (sudo rtcwake -m mem-s 60)
3. Remote wake the DUT by clicking/moving the LE mouse -> **Works fine at this stage**
4. Perform s5 (by clicking on the reboot option from UI)
5. Click/move the LE mouse  to connect back to DUT
6. Put the DUT to CS 
7. Try to wake DUT from CS by clicking/moving the mouse  --> **FAILS here**

[btmon.log](https://github.com/user-attachments/files/17898551/btmon.log)
[btmon_post_sx.log](https://github.com/user-attachments/files/17898553/btmon_post_sx.log)

Bluetoothctl info after connect before CS (step 2 above)
info FA:03:BD:82:B3:61
Device FA:03:BD:82:B3:61 (random)
        Name: M720 Triathlon
        Alias: M720 Triathlon
        Appearance: 0x03c2 (962)
        Icon: input-mouse
        Paired: yes
        Bonded: yes
        Trusted: yes
        Blocked: no
        Connected: yes
        **WakeAllowed: yes**
        LegacyPairing: no
        UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
        UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
        UUID: Device Information        (0000180a-0000-1000-8000-00805f9b34fb)
        UUID: Battery Service           (0000180f-0000-1000-8000-00805f9b34fb)
        UUID: Human Interface Device    (00001812-0000-1000-8000-00805f9b34fb)
        UUID: Vendor specific           (00010000-0000-1000-8000-011f2000046d)
        Modalias: usb:v046DpB015d0013
        AdvertisingFlags:
  05                                               .
        Battery Percentage: 0x64 (100)

Bluetoothctl info after s5 (post step5 above, note: ****WakeAllowed** attribute missing**)
info FA:03:BD:82:B3:62
Device FA:03:BD:82:B3:62 (random)
        Name: M720 Triathlon
        Alias: M720 Triathlon
        Appearance: 0x03c2 (962)
        Icon: input-mouse
        Paired: yes
        Bonded: yes
        Trusted: yes
        Blocked: no
        Connected: yes
        LegacyPairing: no
        UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
        UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
        UUID: Device Information        (0000180a-0000-1000-8000-00805f9b34fb)
        UUID: Battery Service           (0000180f-0000-1000-8000-00805f9b34fb)
        UUID: Human Interface Device    (00001812-0000-1000-8000-00805f9b34fb)
        UUID: Vendor specific           (00010000-0000-1000-8000-011f2000046d)
        Modalias: usb:v046DpB015d0013
        Battery Percentage: 0x64 (100)

**Comment by Vudentz** [comment]
@devegowdIntel please test with the above changes, we should also check with devices using RPA, rather than static random.
