### ISSUE TITLE
DiscoverableTimeout=0 result in Discoverable:no

### ISSUE THREAD

**Issue by koansoftware** [bluez/bluez#139]
Hello,
if I run bluetoothctl show I get Discoverable:no even if I set DiscoverableTimeout = 0 in main.conf.
Looks like 'discoverable' is a property not managed using main.conf therefore I have to set it only though the command 'bluetoothctl discoverable on'.
Is that an expected behaviour?
Thx

**Comment by Vudentz** [comment]
@koansoftware Where did you read that Discoverable is set on main.conf, there is no such entry, there is no persistent setting for Discoverable on purpose since that leaks device information.

**Comment by Vudentz** [comment]
@koansoftware setting discoverable on with bluetoothctl does work as usual:

```
[bluetooth]# discoverable on
Changing discoverable on succeeded
```

The daemon will not persist it though so if you restart the service it will not come back as discoverable again.

**Comment by koansoftware** [comment]
@Vudentz I know that that setting will not persist.
I can't use **bluetoothctl** due to GPLv3 license of **readline**.
I need to make my device (an audio speaker) discoverable and pairable all the time.
What would be the best practice to do that?

**Comment by OrangeDog** [comment]
I'm sure `DiscoverableTimeout = 0` used to make it discoverable from startup. Was it deliberately changed at some point before 5.66?
