### ISSUE TITLE
[5.58] Bluez Mesh - Send : Key not found

### ISSUE THREAD

**Issue by neicureuil** [bluez/bluez#148]
Hi,

I'm trying to make a ble mesh application with the bluez mesh dbus api.
For that, I have two compters under linux. One provisioner and one unprovisioned node.

I have successfully provisioned my node with the provisioner.

I tried to send a message with the `Send` method from the provisionner to the provisioned node, but I get the error : `[org.bluez.mesh.Error.InvalidArgs] Key not found`.

I have generate a key using `void CreateAppKey(uint16 net_index, uint16 app_index)` from the `org.bluez.mesh.Management1` interface but I have the same issue.

What is wrong ?

**Comment by bgix** [comment]
So setting up security is a multi-step process, and it looks like you have:
1. Created your network (auto-creating first local node)
2. Provisioned your next node
3. Created an App Key (I guess on Net Index 0, and a App Index N of your choosing)

Now you need to send that App Key to all nodes that need it, including the Config Client node you created in step 1

4. AddAppKey(<local-ele-obj-path>, dst=0001, app_idx=N, net_idx=0, update=false)
5. AddAppKey(<local-ele-obj-path>, dst=<node from step 2>, app_idx=N, net_idx=0, update=false)

It is good form to then bind the app key to a model on the destinations, but not strictly necessary for  bluetooth-meshd based nodes.  To receive a message on a model, the key used to encrypt the message should be bound. However, regardless the Send method should work now:

6. Send(<local-ele-obj-path>, dst=<node from step 2>, app_idx=N, <data>, <len>)
