### ISSUE TITLE
Bluez Mesh Dbus : Use vendor models

### ISSUE THREAD

**Issue by neicureuil** [bluez/bluez#149]
Hi,

How can I create and handle custom and generic model to use which the mesh API.
I think I need to use the function `void Publish(object element_path, uint16 model, dict options, array{byte} data)` to send a model specific message but I don't know how to generate the model and how to fill the `model` parameter of the function. 

I want to send a message to a specific Vendor Model.

Also, how can I handle message of non generic models ?

**Comment by bgix** [comment]
Hi @neicureuil 

Elements and Models are mostly defined in the user apps using the DBus ObjectManager. The foundational model "Config Server" is provided for the Application by the daemon and handles requests from the Config Client to set up Keys, Publications, Subscriptions etc.  As you have noted, Publish() can be used to send outgoing messages, but only after the Config Client has configured the node for publication, with at least an App Key and Destination Address.  To send messages without being configured for Publication, an App can specify the App key and Destination address directly with Send().

Note that nothing in the messages that flow over the air specify a particular model.. Destination addresses can be either unicast addresses (addressed to a specific element of a specific node), Group address (u16 group addressed managed by Config Client, with multiple recipients) or Virtual UUID addresses (like Group addresses, but uses u128 addresses).

When a message is received by an App, it should validate that the message has an opcode expected by one of it's models, and was encrypted with a key that was bound to the model intended to handle it.


Please refer to the doc/mesh-api.txt for more detailed explanations of the APIs, and refer to the Mesh Profile Specification from the Bluetooth SIG for the concepts used.
