### ISSUE TITLE
[5.9] Kernel module is not loaded automatically at startup

### ISSUE THREAD

**Issue by seo-95** [bluez/bluez#164]
A clean installation of `bluez 5.59-2` causes the `btusb` kernel module to not be loaded automatically on arch linux `5.12.12`. The module has to be loaded manually at each startup and the bluetooth service has to be started consequently.
To solve you need to remove the cache `/var/lib/bluetooth` and downgrade to `bluez <=5.58-1`. Downgrading also `bluez-utils` is not needed.

Other information: https://bbs.archlinux.org/viewtopic.php?id=267428

**Comment by Vudentz** [comment]
I don't think BlueZ does anything for loading kernel modules, this might be something either in the package itself.
