### ISSUE TITLE
Intel AX200 on CentOS 7 set link policy error where bluez version is 5.44

### ISSUE THREAD

**Issue by shuimoshusheng** [bluez/bluez#182]
UP RUNNING 
  RX bytes:12086 acl:60 sco:0 events:271 errors:0
  TX bytes:5472 acl:60 sco:0 commands:179 errors:0
  Features: 0xbf 0xfe 0x0f 0xfe 0xdb 0xff 0x7b 0x87
  Packet type: DM1 DM3 DM5 DH1 DH3 DH5 HV1 HV2 HV3 
  Link policy: RSWITCH SNIFF 
  Link mode: SLAVE ACCEPT 
  Name: 'localhost.localdomain'
  Class: 0x00010c
  Service Classes: Unspecified
  Device Class: Computer, Laptop
  HCI Version:  (0xa)  Revision: 0x100
  LMP Version:  (0xa)  Subversion: 0x100
  Manufacturer: Intel Corp. (2)

[root@bogon ~]# hciconfig hci0 lp HOLD,PARK
Can't set link policy on hci0: Operation not supported (95)

hcidump output is:

> HCI Event: Command Complete (0x0e) plen 4
    Write Default Link Policy Settings (0x02|0x000f) ncmd 1
    status 0x11
    Error: Unsupported Feature or Parameter Value

**Comment by Vudentz** [comment]
This is down to the controller, if it is unsupported it is unsupported by your hardware so nothing to do with BlueZ, also I don't think there is much use of LP command in quite a while, perhaps it was even deprecated in the Bluetooth core spec.
