### ISSUE TITLE
What `--enable-experimental` build flag actually enables?

### ISSUE THREAD

**Issue by ymatsiuk** [bluez/bluez#204]
I'm trying to understand what is the purpose of this flag?

[This](https://github.com/bluez/bluez/blob/8c0c82c9e966654002350ada8489ca577896566a/README#L229) states that it enables tools which are in development currently. I've built `5.61` with this flag enabled and see no difference in files count.
I confused it with `-E/--experimental` argument for `bluetoothd` and now I need to know what is it for? 🙂 

Thanks.

**Comment by Vudentz** [comment]
Currently there is only obexd pcsuite plugin that is affected by this option:

https://github.com/bluez/bluez/blob/master/Makefile.obexd#L26

-E/--experimental (and main.conf Experimental) is for runtime experimental features, as opposed to built-time --enable-experimental.
