### ISSUE TITLE
Media control not working

### ISSUE THREAD

**Issue by Wiedzmin89** [bluez/bluez#209]
I have my headphones connected via bluetooth but media keys not working.

My device connected:
![dfeet0](https://user-images.githubusercontent.com/61706855/134308750-b564a5cd-6dc4-4ba1-a1b1-e8f54ac36de4.png)

But media control does not:
![dfeet](https://user-images.githubusercontent.com/61706855/134308764-7da147fb-03c3-459a-bc36-6368f961deda.png)

And also volume level sync not working. If i understand properly it relates on AVRCP.

Device: Sony WF-1000XM3

Versions:
bluez-git 1:5.61.r50.g9ee79f67b-1
bluez-qt 5.86.0-1

Operating System: Arch Linux
KDE Plasma Version: 5.22.5
KDE Frameworks Version: 5.86.0
Qt Version: 5.15.2
Kernel Version: 5.10.67-1-lts (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i5-8250U CPU @ 1.60GHz
Memory: 15.5 ГиБ of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620

**Comment by Vudentz** [comment]
Please add the HCI traces and daemon logs.

**Comment by Wiedzmin89** [comment]
[bluetooth.txt](https://github.com/bluez/bluez/files/7219667/bluetooth.txt)
[btmon.txt](https://github.com/bluez/bluez/files/7219668/btmon.txt)

**Comment by Vudentz** [comment]
Weird PSM 23 doesn't appear in your logs, I suspect there is something else at play try running bluetoothd from a shell with -dn to see if there any reason why the following is happening:

`сен 23 21:06:45 wiedzmin bluetoothd[448]: src/service.c:btd_service_connect() avrcp-controller profile connect failed for 94:DB:56:7E:1E:54: Input/output error
`

**Comment by Wiedzmin89** [comment]
[bluetoothd.txt](https://github.com/bluez/bluez/files/7220795/bluetoothd.txt)

**Comment by Vudentz** [comment]
You will need to stop the bluetooth.service first, e.g: sudo systemctl stop bluetooth.service, then attempt to connect again.

**Comment by Wiedzmin89** [comment]
[bluetoothd.txt](https://github.com/bluez/bluez/files/7220911/bluetoothd.txt)

**Comment by Vudentz** [comment]
```
bluetoothd[168838]: profiles/audio/avrcp.c:avrcp_controller_server_probe() path /org/bluez/hci0
bluetoothd[168838]: profiles/audio/avctp.c:avctp_server_socket() setsockopt(L2CAP_OPTIONS): Invalid argument (22)
bluetoothd[168838]: avrcp-controller: Protocol not supported (93)
bluetoothd[168838]: profiles/audio/avrcp.c:avrcp_target_server_probe() path /org/bluez/hci0
bluetoothd[168838]: profiles/audio/avctp.c:avctp_server_socket() setsockopt(L2CAP_OPTIONS): Invalid argument (22)
bluetoothd[168838]: audio-avrcp-target: Protocol not supported (93)
```

https://git.kernel.org/pub/scm/linux/kernel/git/bluetooth/bluetooth-next.git/tree/net/bluetooth/l2cap_core.c#n8517

Check if your distro is using disable_ertm that would explain why the protocol is not available.

**Comment by Vudentz** [comment]
@Wiedzmin89 would you able to test with the above changes?

**Comment by Wiedzmin89** [comment]
@Vudentz I tested this version: [https://github.com/tedd-an/bluez/pull/1251](https://github.com/tedd-an/bluez/pull/1251)
Media connected successfully, thanks everyone

**Comment by Wiedzmin89** [comment]
And, yes. It was disable_ertm Y
![image](https://user-images.githubusercontent.com/61706855/134764535-cab30c41-8895-40d0-a506-72762f86dc88.png)
