### ISSUE TITLE
Howto change timeout for "LE Read Remote Used Features"?

### ISSUE THREAD

**Issue by danergo** [bluez/bluez#237]
I'm in a fairly noisy environment, and I need to connect to a bluetooth LE device from Linux using BlueZ (bluetoothctl, gatttool, etc).

When I bring the target device close to the Bluetooth controller (Linux), connection is working perfectly @100% success rate.

However, if I bring the target to its final place, connection only succeeds marginally, let's say @15% success rate.

The problem is that after the Controller sends out the "LE Read Remote Used Features" request, it times out too soon:

```
< HCI Command: LE Read Remote Used Features (0x08|0x0016) plen 2                #11 [hci0] 9.678198
        Handle: 0
> HCI Event: Command Status (0x0f) plen 4                                       #12 [hci0] 9.683707
      LE Read Remote Used Features (0x08|0x0016) ncmd 5
        Status: Success (0x00)
> HCI Event: Disconnect Complete (0x05) plen 4                                  #13 [hci0] 9.966938
        Status: Success (0x00)
        Handle: 0
        Reason: Connection Failed to be Established (0x3e)
@ MGMT Event: Device Disconnected (0x000c) plen 8                          {0x0001} [hci0] 9.967055
        LE Address: TARGET_MAC (TARGET)
        Reason: Unspecified (0x00)
```

Too soon here equals to 0.28s after the request.

How can I change this timeout to be a little bit less aggressive?

(Tried changing the supervision_timeout, but that haven't made any progress)

**Comment by Vudentz** [comment]
Im afraid this is down in the link layer which is part of the controller firmware, iirc the Connection Complete on LE doesn't actually mean the connection was stabilished but that the controller was able to find the device over the air and started the connection procedure but it can still fail to establish which is why te error Connection Failed to be Established (0x3e) is returned.
