### ISSUE TITLE
g_memdup was deprecated in glib 2.68, use g_memdup2 instead

### ISSUE THREAD

**Issue by UweSauter** [bluez/bluez#271]
Quoting [Glib documentation](https://developer-old.gnome.org/glib/stable/glib-Memory-Allocation.html#g-memdup):
```
g_memdup has been deprecated since version 2.68 and should not be used in newly-written code.

Use g_memdup2() instead, as it accepts a gsize argument for byte_size,
avoiding the possibility of overflow in a gsize → guint conversion
```

Current occurrences:

- client/gatt.c:814
- tools/mesh-gatt/gatt.c:341
- tools/gatt-service.c:130
- tools/gatt-service.c:268
- tools/gatt-service.c:595
- gobex/gobex-packet.c:204
- gobex/gobex-header.c:225
- gobex/gobex-header.c:413
- plugins/policy.c:858
- plugins/policy.c:889
- profiles/audio/avctp.c:1730
- profiles/audio/avctp.c:1768
- profiles/audio/avrcp.c:1301
- profiles/audio/avrcp.c:2804
- profiles/audio/avrcp.c:2891
- profiles/input/hog-lib.c:532
- profiles/input/hog-lib.c:1612
- profiles/input/hog-lib.c:1626
- profiles/deviceinfo/dis.c:146
- profiles/battery/bas.c:78
- profiles/scanparam/scpp.c:113
- profiles/battery/battery.c:162
- attrib/gatt.c:699
- attrib/gatt.c:967
- attrib/gatt.c:1133
- src/attrib-server.c:342
- src/eir.c:326
- src/eir.c:332
- gobex/gobex-packet.c:204
- gobex/gobex-header.c:225
- gobex/gobex-header.c:413
- obexd/src/obex.c:597

File list was taken from compiler warnings.

**Comment by Vudentz** [comment]
This has already been address by:

https://git.kernel.org/pub/scm/bluetooth/bluez.git/commit/?id=cfab569484b18407fc117bb96634525cc76ea1f5
