### ISSUE TITLE
Failed to transfer file to Windows

### ISSUE THREAD

**Issue by lishengyu** [bluez/bluez#279]
My bluez version is 5.50. 

When I transfer file to windows, it always fails.

I suspect that the problem is in the response package of SDP by confirming the code and capturing the protocol package analysis.
![image](https://user-images.githubusercontent.com/9626490/150902123-552f23e1-2c56-4f48-b1d5-75f5544e214f.png)

![image](https://user-images.githubusercontent.com/9626490/150902057-a6daa324-d5e2-4c2d-ac13-7b4e64c3410a.png)

I don't know how to get out next, do there have any suggestions?

**Comment by Vudentz** [comment]
@lishengyu it seem the remote device don't support OPP or whatever you are trying to look for.

**Comment by lishengyu** [comment]
@Vudentz    Thanks very much!

The SDP request packet is as follows:
![image](https://user-images.githubusercontent.com/9626490/150938562-6c529949-91b3-40b2-b6fd-ae164ac39817.png)

Do I have any means to further confirm this problem? Or more specifically, how can I verify that the remote device supports OPP or not ?

**Comment by Vudentz** [comment]
@lishengyu well the trace above already confirms it doesn't support OPP, perhaps windows uses a different profile (or you have to enable it somehow).

**Comment by lishengyu** [comment]
@Vudentz  Ok, I will try to confirm the problem on the Windows side. If there are more details, I will communicate with you then.
