### ISSUE TITLE
Segfault reconnecting to Jabra Evolve2 85 headset

### ISSUE THREAD

**Issue by senorsnor** [bluez/bluez#292]
My Jabra Evolve2 85 bluetooth headset is paired to my laptop running Arch Linux. When I turn the headset off, then turn it on again, it reconnects (both blueman-applet and the headset indicate that it is connected), and then the bluetooth service exits with a segmentation fault. Stacktrace below is from the moment I switch the headset back on:

    Feb 13 19:58:27 kitten pulseaudio[627]: Device doesn't exist for /org/bluez/hci0/dev_70_BF_92_E0_D0_26
    Feb 13 19:58:27 kitten bluetoothd[51116]: src/profile.c:new_conn_reply() Hands-Free Voice gateway replied with an error: org.bluez.Error.InvalidArguments, Unable to handle new connection
    Feb 13 19:58:28 kitten pulseaudio[627]: Device doesn't exist for /org/bluez/hci0/dev_70_BF_92_E0_D0_26
    Feb 13 19:58:28 kitten bluetoothd[51116]: src/profile.c:new_conn_reply() Hands-Free Voice gateway replied with an error: org.bluez.Error.InvalidArguments, Unable to handle new connection
    Feb 13 19:58:29 kitten pulseaudio[627]: Information about device /org/bluez/hci0/dev_70_BF_92_E0_D0_26 is invalid
    Feb 13 19:58:29 kitten bluetoothd[51116]: profiles/audio/media.c:endpoint_reply() Endpoint replied with an error: org.bluez.Error.InvalidArguments
    Feb 13 19:58:30 kitten audit[51116]: ANOM_ABEND auid=4294967295 uid=0 gid=0 ses=4294967295 pid=51116 comm="bluetoothd" exe="/usr/lib/bluetooth/bluetoothd" sig=11 res=1
    Feb 13 19:58:30 kitten kernel: bluetoothd[51116]: segfault at 55bff94e0 ip 00007f2ee5287547 sp 00007ffdadc657f8 error 4 in libc-2.33.so[7f2ee514d000+14b000]
    Feb 13 19:58:30 kitten kernel: Code: 85 c0 0f 85 eb 00 00 00 48 83 c7 20 83 e1 1f 48 83 e7 e0 eb 42 66 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 00 83 e1 1f 48 83 e7 e0 <c5> fd 74 0f c5 fd d7 c1 >
    Feb 13 19:58:30 kitten kernel: audit: type=1701 audit(1644778710.315:264): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=51116 comm="bluetoothd" exe="/usr/lib/bluetooth/bluetoothd" sig=11 >
    Feb 13 19:58:30 kitten audit: BPF prog-id=36 op=LOAD
    Feb 13 19:58:30 kitten audit: BPF prog-id=37 op=LOAD
    Feb 13 19:58:30 kitten audit: BPF prog-id=38 op=LOAD
    Feb 13 19:58:30 kitten systemd[1]: Started Process Core Dump (PID 142443/UID 0).
    Feb 13 19:58:30 kitten audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@1-142443-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr>
    Feb 13 19:58:30 kitten kernel: audit: type=1334 audit(1644778710.335:265): prog-id=36 op=LOAD
    Feb 13 19:58:30 kitten kernel: audit: type=1334 audit(1644778710.339:266): prog-id=37 op=LOAD
    Feb 13 19:58:30 kitten kernel: audit: type=1334 audit(1644778710.339:267): prog-id=38 op=LOAD
    Feb 13 19:58:30 kitten kernel: audit: type=1130 audit(1644778710.339:268): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@1-142443-0 comm="systemd" exe="/usr/lib/syst>
    Feb 13 19:58:30 kitten systemd-coredump[142444]: [🡕] Process 51116 (bluetoothd) of user 0 dumped core.
                                                 
                                                 Module linux-vdso.so.1 with build-id c383727bad7b2b0dc9d2be991ee2f300d229360a
                                                 Module libgpg-error.so.0 with build-id 82524ee3d1c4c2244d7cfdcc1e6eea5f9855f6c6
                                                 Module libgcc_s.so.1 with build-id 7f8508bb914546ada778809b64b99d234337d835
                                                 Module libgcrypt.so.20 with build-id db45f5d5e0f7af1e77324fea1885f974619ad268
                                                 Module libcap.so.2 with build-id eb6dae97527fc89dbb0d5bb581a15acd02ae9f56
                                                 Module liblz4.so.1 with build-id e63600ab23b2f6997f42fac2fa56e1f02ce159a1
                                                 Module libzstd.so.1 with build-id 72f3511cba7db578f6a2647925f35664da6c838b
                                                 Module liblzma.so.5 with build-id 8b615460aa230708c5183f16bede67aa0437d95e
                                                 Module librt.so.1 with build-id 75484da2d6f1515189eefa076e0a40328834cd16
                                                 Module libm.so.6 with build-id 2b8fd1f869ecab4e0b55e92f2f151897f6818acf
                                                 Module ld-linux-x86-64.so.2 with build-id 040cc3dd10461562f177df39e3be2f3704258c3c
                                                 Module libsystemd.so.0 with build-id a83a62063b8098eda274d25251d619f0503bf011
                                                 Module libpthread.so.0 with build-id 07c8f95b4f3251d08550217ad8a1f31066229996
                                                 Module libpcre.so.1 with build-id 845483dd0acba86de9f0313102bebbaf3ce52767
                                                 Module libc.so.6 with build-id 4b406737057708c0e4c642345a703c47a61c73dc
                                                 Module libasound.so.2 with build-id b17fc1317a484842433c772360376623b64ec3d8
                                                 Module libdl.so.2 with build-id 5abc547e7b0949f89f3c0e21ab0c8331a7440a8a
                                                 Module libdbus-1.so.3 with build-id 74f2ab9c60512f3a93c932c3f627564d42e0b11e
                                                 Module libglib-2.0.so.0 with build-id bd949a4794ad959019499c6afcb8f416dcff9810
                                                 Module bluetoothd with build-id 5525c0571ff90afd826ab20e87cbda7a2c47061c
                                                 Stack trace of thread 51116:
                                                 #0  0x00007f2ee5287547 __strlen_avx2 (libc.so.6 + 0x160547)
                                                 #1  0x00007f2ee5416246 _dbus_string_init_const (libdbus-1.so.3 + 0x34246)
                                                 #2  0x00007f2ee5401be9 n/a (libdbus-1.so.3 + 0x1fbe9)
                                                 #3  0x00007f2ee5404699 dbus_message_iter_append_basic (libdbus-1.so.3 + 0x22699)
                                                 #4  0x00007f2ee540522f dbus_message_append_args_valist (libdbus-1.so.3 + 0x2322f)
                                                 #5  0x00007f2ee54054ea dbus_message_append_args (libdbus-1.so.3 + 0x234ea)
                                                 #6  0x000055bff8b179f5 n/a (bluetoothd + 0x359f5)
                                                 #7  0x000055bff8b081b8 n/a (bluetoothd + 0x261b8)
                                                 #8  0x00007f2ee54a8680 g_slist_foreach (libglib-2.0.so.0 + 0x71680)
                                                 #9  0x000055bff8b10438 n/a (bluetoothd + 0x2e438)
                                                 #10 0x000055bff8b105bd n/a (bluetoothd + 0x2e5bd)
                                                 #11 0x000055bff8b9f231 n/a (bluetoothd + 0xbd231)
                                                 #12 0x00007f2ee548c708 n/a (libglib-2.0.so.0 + 0x55708)
                                                 #13 0x00007f2ee548bf13 g_main_context_dispatch (libglib-2.0.so.0 + 0x54f13)
                                                 #14 0x00007f2ee54e20d9 n/a (libglib-2.0.so.0 + 0xab0d9)
                                                 #15 0x00007f2ee548b463 g_main_loop_run (libglib-2.0.so.0 + 0x54463)
                                                 #16 0x000055bff8b02742 n/a (bluetoothd + 0x20742)
                                                 #17 0x00007f2ee514eb25 __libc_start_main (libc.so.6 + 0x27b25)
                                                 #18 0x000055bff8b041ae n/a (bluetoothd + 0x221ae)
                                                 ELF object binary architecture: AMD x86-64
    Feb 13 19:58:30 kitten systemd[1]: bluetooth.service: Main process exited, code=dumped, status=11/SEGV
    Feb 13 19:58:30 kitten kernel: audit: type=1131 audit(1644778710.409:269): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=bluetooth comm="systemd" exe="/usr/lib/systemd/systemd" hostn>
    Feb 13 19:58:30 kitten kernel: audit: type=1131 audit(1644778710.409:270): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@1-142443-0 comm="systemd" exe="/usr/lib/syst>
    Feb 13 19:58:30 kitten audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=bluetooth comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=f>
    Feb 13 19:58:30 kitten audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@1-142443-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=>
    Feb 13 19:58:30 kitten systemd[1]: bluetooth.service: Failed with result 'core-dump'.
    Feb 13 19:58:30 kitten NetworkManager[426]: <info>  [1644778710.4125] device (D4:38:9C:45:8A:60): state change: disconnected -> unmanaged (reason 'removed', sys-iface-state: 'removed')
    Feb 13 19:58:30 kitten systemd[1]: systemd-coredump@1-142443-0.service: Deactivated successfully.

I'm running:
blueman 2.2.3-2
bluez 5.63-1
bluez-libs 5.63-1
bluez-utils 5.63-1
pulseaudio-bluetooth 15.0-1

I'm not an expert in this, please let me know how I can help troubleshoot the issue to get the cause clear for you. Thanks for all your work.

**Comment by Vudentz** [comment]
@senorsnor try testing with git latest since we did fix a couple crashes like this.

**Comment by senorsnor** [comment]
Seems to work indeed, thanks a lot!
