### ISSUE TITLE
Help dealing with spamming of log due to #286

### ISSUE THREAD

**Issue by DanHam** [bluez/bluez#295]
Hi,

I'm affected by #286. `journalctl` shows bluetoothd outputting the following every second.

```
Feb 17 16:18:28 tink bluetoothd[1514]: src/adv_monitor.c:btd_adv_monitor_offload_supported() Manager is NULL, get offload support failed
Feb 17 16:18:29 tink bluetoothd[1514]: src/adv_monitor.c:btd_adv_monitor_offload_supported() Manager is NULL, get offload support failed
```

I realise #286 has been closed by way of https://github.com/bluez/bluez/commit/264177eb4ae8acd368668243b93e7769455b8bf5. 

Clearly, until this fix works its way into my distribution my logs are still getting spammed.

Is there a way to tell bluetoothd to not log this error in the meantime?

**Comment by Vudentz** [comment]
Not really, but we will be releasing 5.64 soon.
