### ISSUE TITLE
org.bluez.Device1: Difference between Connected signal and return of the Connect() method

### ISSUE THREAD

**Issue by vl-80** [bluez/bluez#315]
Could someone explain the difference between the `Connected` property being set to `TRUE` vs successful return of the `Connect()` method of the `org.bluez.Device1` interface?

It appears that when connecting to a Bluetooth LE device, the `Connected` property is set to `TRUE` first (indicated by the arrival of the signal) and then couple of seconds later the `Connect()` method returns with a success.

So, what exactly are these two separate events signifying?

Does the `Connected` property indicate establishment of the low level connection while the return of the `Connect()` method indicates the establishment of some higher level connection (connection to a Profile)?

**Comment by Vudentz** [comment]
@vl-80 yes, Connected is sent whenever the ACL link is established while Connect will then attempt to connect any supported profiles that is marked to auto-connect.
