### ISSUE TITLE
Current State of Autoconnect Logic

### ISSUE THREAD

**Issue by p0da** [bluez/bluez#331]
Just wanted to inquire about the current state of the autoconnect logic in bluez as despite my best efforts I have yet to get any of my peripherals to dependably autoconnect to my controller despite the fact that they are all paired and trusted beforehand. Searching online it seems like this has been a fairly common issue from 5+ years ago to this very day with a [python script](https://github.com/jrouleau/bluetooth-autoconnect) even being written to rectify the issue. While the script works for me, I would prefer to use a native solution especially if it is already built into bluez. Thanks for the help.

**Comment by Vudentz** [comment]
@p0da I assume you are talking about LE peripheral, with BR/EDR the peripheral has to actually initiate the connection as there is no concept of passive scanning like LE. BlueZ logic to auto-connect is based on having matching profiles/services, so a peripheral that does implement something HoG will have its address programmed in the so called allow list and enable passive scanning, perhaps you don't have a matching profiles/service? You can check if auto-connect flag is being set with btmon:

```
@ MGMT Command: Add Device (0x0033) plen 8                                                                                                 {0x0001} [hci0] 14:31:01.244347
        LE Address: 41:1E:E2:XX:XX:XX (OUI 41-1E-E2)
        Action: Auto-connect remote device (0x02)
```
