### ISSUE TITLE
error: ‘VIDEO_CONF_SVCLASS_ID’ undeclared here

### ISSUE THREAD

**Issue by wbehrens-on-gh** [bluez/bluez#349]
I'm stuck using a very old release of BlueZ for a project (4.80) and this is more of a question as I have a feeling the solution is just passing the right configure flags but here it goes.

I'm on BlueZ 4.80 building on Ubuntu 20.04 using GCC 9 but I keep running into the error

```
src/glib-helper.c:433:11: error: ‘VIDEO_CONF_SVCLASS_ID’ undeclared here (not in a function); did you mean ‘VIDEO_CONF_GW_SVCLASS_ID’?
  433 |  { "vcp", VIDEO_CONF_SVCLASS_ID  },
      |           ^~~~~~~~~~~~~~~~~~~~~
      |           VIDEO_CONF_GW_SVCLASS_ID
make[1]: *** [Makefile:2640: src/glib-helper.o] Error 1
make: *** [Makefile:1411: all] Error 2
```

after running `./configure --disable-service` and `make`

**Comment by back2childhood** [comment]
I have the same question today, do u know how to deal with it today?
