### ISSUE TITLE
Bluetoothctl - write call is returning not supported error

### ISSUE THREAD

**Issue by santhosh12992** [bluez/bluez#35]
Hi, am able to do the write call with two bytes of data. However, it returns a not supported error when I send more than 2 hex bytes to data.

```
[C by GE:/service0010/char001a]# write 0x0c 0x90 0x9d 0x15 0x11 0x65 0xda 0xad 0x2d 0xa1 0x19 0x81 0x8b 0x72 0xd5 0xa4 0xae
Attempting to write /org/bluez/hci0/dev_A4_C1_38_E6_92_1C/service0010/char001a
Failed to write: org.bluez.Error.NotSupported
[C by GE:/service0010/char001a]# write 0x0c 0x90 
Attempting to write /org/bluez/hci0/dev_A4_C1_38_E6_92_1C/service0010/char001a
[C by GE:/service0010/char001a]#


smuralik@smuralik-NUC8i7BEH:~/Documents/0b7a162995d0b465ba9c84728e60ec01-b1c0984fe241bf94a0e652947354ed22e9d0de0e$ bluetoothctl -V
bluetoothctl: invalid option -- 'V'
bluetoothctl ver 5.54
Usage:
	bluetoothctl [--options] [commands]
Options:
	--agent 	Register agent handler: <capability>
	--monitor 	Enable monitor output
	--timeout 	Timeout in seconds for non-interactive mode
	--version 	Display version
	--help 		Display help

```

Do I miss something before the write call. I have checked twice, thrice and I am writing to the correct characteristics. 
Kindly let me know, If I need to provide more data.

Thanks.
Santhoshkumar M

**Comment by Vudentz** [comment]
bluetooth> gatt.write <data=xx xx ...> [offset] [type]

So you if you want to send multiple bytes you will need to group then with "", otherwise you would be setting offset and type.

bluetoothctl> gatt.write "0x0c 0x90 0x9d 0x15 0x11 0x65 0xda 0xad 0x2d 0xa1 0x19 0x81 0x8b 0x72 0xd5 0xa4 0xae"
