### ISSUE TITLE
Gatttool in bluez 5.50-1.2 after setting mtu always crashes

### ISSUE THREAD

**Issue by jnsw** [bluez/bluez#361]
Hello,

I am using bluez in the version 5.50-1.2~deb10u2+rpt1 armhf on my RPi4 installed freshly from `sudo apt install bluez`, but I cant make the commands like in the following picture: 

<img width="1068" alt="image" src="https://user-images.githubusercontent.com/7985146/175887784-4e281c95-0308-4453-9568-e8c0d2c345ba.png">

But if I am doing the same in bluez version 5.50-1+rpt1 armhf on another (older) Pi4, where I did not updated the package, I can set the mtu and get all the characteristics.

Is this behaviour wanted? Do I ask in the right place?

Greetings
Jan

**Comment by Vudentz** [comment]
@jnsw gatttool is deprecated, please use bluetoothctl gatt menu. As for MTU bluetoothd negotiates the maximum MTU already.
