### ISSUE TITLE
BNEP protocol unsupported, but built-in into kernel

### ISSUE THREAD

**Issue by DylanVanAssche** [bluez/bluez#368]
I'm trying to setup a NAP server to search my internet connection over Bluetooth with devices.
This part is handled by the `network` plugin in BlueZ.

However, when BlueZ starts up, it says that BNEP is unsupported  in the kernel which is required for this feature.

```
bluetoothd[8128]: profiles/network/bnep.c:bnep_init() kernel lacks bnep-protocol support
```

I checked my kernel config and BNEP is enabled as a built-in module, so it should support that.

```
shift-axolotl:~$ cat /proc/config.gz | gunzip | grep BNEP
CONFIG_BT_BNEP=y
CONFIG_BT_BNEP_MC_FILTER=y
CONFIG_BT_BNEP_PROTO_FILTER=y
```

Is there anything I could do to debug this?

**Comment by thbonotto** [comment]
Were you able to fix it? 

I was facing the same issue, I noticed that my Kernel config had `CONFIG_BT=m`, so I changed CONFIG_BT_BNEP to `CONFIG_BT_BNEP=m` too, and it worked.

You may need to change **CONFIG_BT_BNEP_MC_FILTER** and **CONFIG_BT_BNEP_PROTO_FILTER** to:

```
CONFIG_BT_BNEP_MC_FILTER=m
CONFIG_BT_BNEP_PROTO_FILTER=m
```

**Comment by DylanVanAssche** [comment]
Turns out the MAC address of the Bluetooth adapter was invalid... I fixed that now and it works fine!
