### ISSUE TITLE
I cant scan hdp device

### ISSUE THREAD

**Issue by Dream4Theater** [bluez/bluez#375]
![image](https://user-images.githubusercontent.com/81992744/184659553-99d108ec-8c78-4ee9-872d-bff21717b151.png)
I cant scan hdp device. I have a omron 708-bt device and i cant read any data from it. And i am using this code to scan hdp device but i can't scan any device because of this mistake

**Comment by Vudentz** [comment]
@Dream4Theater It doesn't seem that have any tool with such name on BlueZ tree? Perhaps this comes from a different project and in that case you should probably file a bug report to that project not here.
