### ISSUE TITLE
BLE secure pairing implementation

### ISSUE THREAD

**Issue by laurislopata** [bluez/bluez#381]
I am currently developing a BLE communication system where an app on the phone will communicate with a peripheral device. I am working on both the BLE client on the phone and the BLE server on the peripheral

For the app part, I'm using react-native-ble-manager and for the ble server part, I based it on examples from the official BLE docs using dbus and Python.

I want to add some security to the pairing process, by implementing the PIN security mechanism or just saving the same private key and verifying the connection is trustworthy but after spending some time researching how this should be implemented I did not find any good examples. Where could I find some resources or guidelines on how to implement these security mechanisms?

**Comment by Vudentz** [comment]
@laurislopata Bluetooth has many pairing options, you just need to set it in the D-Bus object property Flags:

https://github.com/bluez/bluez/blob/master/doc/gatt-api.txt#L263

encrypt-* (can use just works pairing) -> encrypt-authenticated (requires MITM protection) -> secure-* (requires Secure Connections)

The pairing process itself is done via pairing agent:

https://github.com/bluez/bluez/blob/master/doc/agent-api.txt
