### ISSUE TITLE
i have a crash（_dbus_object_tree_dispatch_and_unlock ） ,Has anyone met？

### ISSUE THREAD

**Issue by FreshLuoBoGan** [bluez/bluez#394]
![image](https://user-images.githubusercontent.com/28969782/190387582-9f660869-450a-4612-960a-4200a607dee8.png)

**Comment by Vudentz** [comment]
@FreshLuoBoGan not really, what is bdmanager though?

**Comment by FreshLuoBoGan** [comment]
the bdmanager is my app，it integrate bluez-client;

**Comment by FreshLuoBoGan** [comment]
> @FreshLuoBoGan not really, what is bdmanager though?

and the object.c is from bluez-5.64/gdbus/object.c

**Comment by Vudentz** [comment]
> > @FreshLuoBoGan not really, what is bdmanager though?
> 
> and the object.c is from bluez-5.64/gdbus/object.c

You are no supposed to link with it though, it is GPL and not thread safe which is probably why you are having problems.

**Comment by FreshLuoBoGan** [comment]
> > > @FreshLuoBoGan not really, what is bdmanager though?
> > 
> > 
> > and the object.c is from bluez-5.64/gdbus/object.c
> 
> You are no supposed to link with it though, it is GPL and not thread safe which is probably why you are having problems.

ok,thank you ,i try to solve it

**Comment by FreshLuoBoGan** [comment]
i resolved it，my app is multithread,so i add mutex in pending of object.c，thank you for your remind @Vudentz
