### ISSUE TITLE
In bluez 5.66 No device with  phy of 2m was scanned 

### ISSUE THREAD

**Issue by michealSae** [bluez/bluez#439]
I can't scan any 2m LE sensor on my devices which was fine in bluez 5.50.
When` bluetoothctl scan on`, i can capture my 2m LE sensor  with `btmon`.

here is the bluetoothctl show 

```
Controller 34:DA:C1:A0:08:88 (public)
        Name: BlueZ 5.66
        Alias: BlueZ 5.66
        Class: 0x00000000
        Powered: yes
        PowerState: on
        Discoverable: no
        DiscoverableTimeout: 0x000000b4
        Pairable: yes
        UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
        UUID: Device Information        (0000180a-0000-1000-8000-00805f9b34fb)
        UUID: Handsfree                 (0000111e-0000-1000-8000-00805f9b34fb)
        UUID: PnP Information           (00001200-0000-1000-8000-00805f9b34fb)
        UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
        Modalias: usb:v1D6Bp0246d0542
        Discovering: yes
        Roles: central
        Roles: peripheral
Advertising Features:
        ActiveInstances: 0x00 (0)
        SupportedInstances: 0x01 (1)
        SupportedIncludes: tx-power
        SupportedIncludes: local-name
        SupportedCapabilities Key: MaxAdvLen
        SupportedCapabilities Value: 0x1f (31)
        SupportedCapabilities Key: MaxScnRspLen
        SupportedCapabilities Value: 0x1f (31)
Advertisement Monitor Features:
        SupportedMonitorTypes: or_patterns

```

here is the btmon capture, and` 34:DA:C1:11:00:2A ` was my sensor .

```
> HCI Event: LE Meta Event (0x3e) plen 37                                                                                                                                                                         #200 [hci0] 28.774451
      LE Advertising Report (0x02)
        Num reports: 1
        Event type: Connectable undirected - ADV_IND (0x00)
        Address type: Public (0x00)
        Address: 34:DA:C1:11:00:2A (OUI 34-DA-C1)
        Data length: 25
        Flags: 0x06
          LE General Discoverable Mode
          BR/EDR Not Supported
        Company: TDK Corporation (1549)
          Data: 110f011016233c00d00703023c08071650
        07                                               .
        RSSI: -57 dBm (0xc7)
> HCI Event: LE Meta Event (0x3e) plen 36                                                                                                                                                                         #201 [hci0] 28.779893
      LE Advertising Report (0x02)
        Num reports: 1
        Event type: Scan response - SCAN_RSP (0x04)
        Address type: Public (0x00)
        Address: 34:DA:C1:11:00:2A (OUI 34-DA-C1)
        Data length: 24
        Name (complete): CN2202B11002A
        TX power: 5 dBm
        Peripheral Conn. Interval: 0x0006 - 0x0140
        RSSI: -59 dBm (0xc5)
```

**Comment by Vudentz** [comment]
> here is the btmon capture, and`34:DA:C1:11:00:2A` was my sensor .
> 
> ```
> > HCI Event: LE Meta Event (0x3e) plen 37                                                                                                                                                                         #200 [hci0] 28.774451
>       LE Advertising Report (0x02)
>         Num reports: 1
>         Event type: Connectable undirected - ADV_IND (0x00)
>         Address type: Public (0x00)
>         Address: 34:DA:C1:11:00:2A (OUI 34-DA-C1)
>         Data length: 25
>         Flags: 0x06
>           LE General Discoverable Mode
>           BR/EDR Not Supported
>         Company: TDK Corporation (1549)
>           Data: 110f011016233c00d00703023c08071650
>         07                                               .
>         RSSI: -57 dBm (0xc7)
> > HCI Event: LE Meta Event (0x3e) plen 36                                                                                                                                                                         #201 [hci0] 28.779893
>       LE Advertising Report (0x02)
>         Num reports: 1
>         Event type: Scan response - SCAN_RSP (0x04)
>         Address type: Public (0x00)
>         Address: 34:DA:C1:11:00:2A (OUI 34-DA-C1)
>         Data length: 24
>         Name (complete): CN2202B11002A
>         TX power: 5 dBm
>         Peripheral Conn. Interval: 0x0006 - 0x0140
>         RSSI: -59 dBm (0xc5)
> ```

So are the actual bug that you don't see updates over D-Bus? e.g like a new device signal, etc? I can see it is marked as discoverable, but perhaps you already have it paired before hand that way it wouldn't generate a new device just update the existing D-Bus object.

**Comment by michealSae** [comment]
I made a really stupid mistake and didn't set Transport = le .
```
filter = {
                'RSSI': dbus.Int16(-95),
                'Transport': 'le'
                }
            self.adapter_interface.SetDiscoveryFilter(filter)
```
@Vudentz   Thank you for your reply.
But i have another problem, that bluetoothd may abort, when i call `Connect` too often.
 I have described my problem in a new [issue](https://github.com/bluez/bluez/issues/440)
