### ISSUE TITLE
NoInputNoOutput is not working

### ISSUE THREAD

**Issue by onurcoskun14** [bluez/bluez#474]
System features 
Bluez version : 5.55
Kernel version : 5.15.84-v7+

I have a android application that connects the rpi and reads the data from characteristic. I am using rpi as headless so user should be able to connect from mobile phone to rpi without any verification. But when i try to use NoInputNoOutput the connection never happens.

![image](https://user-images.githubusercontent.com/117642438/218083885-f07cf241-2009-4ee0-aa5a-e2d1c70486a4.png)

**Comment by Vudentz** [comment]
@onurcoskun14 you probably need to unregister the agent first:

```
[bluetooth]# agent off
Agent unregistered
[bluetooth]# agent NoInputNoOutput 
Agent registered

```
