### ISSUE TITLE
btvirt create local controller，but can‘t use it

### ISSUE THREAD

**Issue by jjj19950710** [bluez/bluez#489]
I run the command:
```
sudo btvirt -l
```
it create one controller hci1,I can power on,but when I scan it do nothing.I can't do any scanning, pairing and connection through the hci1 controller.how can I use virtual controller hci1 to pair remote bluetooth device？

**Comment by Vudentz** [comment]
@jjj19950710 it is an emulated instance, it doesn't actually do any real RF traffic, so it only works with other emulated instances created by btvirt.
