### ISSUE TITLE
advertising headers added to wrong place in the "Row data"

### ISSUE THREAD

**Issue by bwomsm1** [bluez/bluez#496]
I am sending an advertising ble message and successfully manage to see the adverting in android `nRF Connect` mobile app.

But when I open the blue `RAW` button in the app and looking at the `Raw data:` section, 
I noticed that the packet is being sent when the advertising headers are added to the end of the raw data instead of the beginning 
0x15FFA703641E610001BE000A5832D964030409000207**020106**

Explain about the data (**15 - FF - A703 - 641E610001BE000A5832D964030409000207 - 020106** )
15 - is the size of my payload
FF - is the start byte of the manufacture data
A703 - is my company BLE manufacture name, "AeroScout" (A703)
641E610001BE000A5832D964030409000207 - is my manufacture data
**020106** - Why is it in the end? it should be just before the 15

The correct string which I should see in the `Raw data:` is 
0x**020106**15FFA703641E610001BE000A5832D964030409000207

![Screenshot_20230329-131334_nRF Connect](https://user-images.githubusercontent.com/5571230/228504343-27753713-000b-459d-9e98-af98dae94c2e.jpg)

**Comment by Vudentz** [comment]
> @grinya007 @Vudentz do you mind taking a look on the bug/question above? THANKS!

The advertising data is in LTV format, so it doesn't matter in which order it is placed, so len 0x02 type 0x01 (BT_AD_FLAGS) value 0x06 (BT_AD_FLAG_GENERAL | BT_AD_FLAG_NO_BREDR), that said it is probably a good idea to prepend in case of the flags but there is nothing wrong if we append either.

**Comment by bwomsm1** [comment]
Thanks @Vudentz. we can close the ticket from my side
