### ISSUE TITLE
[Q] How to refresh SDP services of a device, or remove a SDP service entry?

### ISSUE THREAD

**Issue by boilerman** [bluez/bluez#5]
As I said in the previous posting:
> So we have to make a Windows PC work as a HID device (working in Across Server mode which make SDP service available) to pair with a Linux PC.
> .... All that I am mentioning is need only for a pairing process to succeed.

For pairing with a Windows PC, I made a Windows have a HID SDP service, but it is needed only in a pairing process, I want to refresh SDP service of the Win PC, or remove the HID SDP service entry after pairing done, but failed to find a relevant method to do that.

I think bluez must have a measure to do that if it doesn't have yet, since a BT device could publish/remove SDP service at its will. If bluez have an outdated SDP entry, bluez could go wrong easily.
Anyway, thanks for the nice BT stack! :)

**Comment by Vudentz** [comment]
We keep a cache of SDP records and update it everytime the device connects.
