### ISSUE TITLE
 Bluez 5.55 update shows errors each system boot

### ISSUE THREAD

**Issue by aureoud-fr85** [bluez/bluez#51]
Since bluez 5.55 update on sat. Sept, 19th 2020,

journalctl --unit=bluetooth.service :
systemd[1]: Starting Bluetooth service...
bluetoothd[1416]: Bluetooth daemon 5.55
bluetoothd[1416]: src/main.c:parse_controller_config() Key file does not have key “BRPageScanType” in group “Controller”
bluetoothd[1416]: src/main.c:parse_controller_config() Key file does not have key “BRPageScanInterval” in group “Controller”
bluetoothd[1416]: src/main.c:parse_controller_config() Key file does not have key “BRPageScanWindow” in group “Controller”
bluetoothd[1416]: src/main.c:parse_controller_config() Key file does not have key “BRInquiryScanType” in group “Controller”
bluetoothd[1416]: src/main.c:parse_controller_config() Key file does not have key “BRInquiryScanInterval” in group “Controller”
bluetoothd[1416]: src/main.c:parse_controller_config() Key file does not have key “BRInquiryScanWindow” in group “Controller”
bluetoothd[1416]: src/main.c:parse_controller_config() Key file does not have key “BRLinkSupervisionTimeout” in group “Controller”
bluetoothd[1416]: src/main.c:parse_controller_config() Key file does not have key “BRPageTimeout” in group “Controller”
bluetoothd[1416]: src/main.c:parse_controller_config() Key file does not have key “BRMinSniffInterval” in group “Controller”
bluetoothd[1416]: src/main.c:parse_controller_config() Key file does not have key “BRMaxSniffInterval” in group “Controller”
bluetoothd[1416]: src/main.c:parse_controller_config() Key file does not have key “LEMinAdvertisementInterval” in group “Controller”
bluetoothd[1416]: src/main.c:parse_controller_config() Key file does not have key “LEMaxAdvertisementInterval” in group “Controller”
bluetoothd[1416]: src/main.c:parse_controller_config() Key file does not have key “LEMultiAdvertisementRotationInterval” in group “Controller”
bluetoothd[1416]: src/main.c:parse_controller_config() Key file does not have key “LEScanIntervalAutoConnect” in group “Controller”
bluetoothd[1416]: src/main.c:parse_controller_config() Key file does not have key “LEScanWindowAutoConnect” in group “Controller”
bluetoothd[1416]: src/main.c:parse_controller_config() Key file does not have key “LEScanIntervalSuspend” in group “Controller”
bluetoothd[1416]: src/main.c:parse_controller_config() Key file does not have key “LEScanWindowSuspend” in group “Controller”
bluetoothd[1416]: src/main.c:parse_controller_config() Key file does not have key “LEScanIntervalDiscovery” in group “Controller”
bluetoothd[1416]: src/main.c:parse_controller_config() Key file does not have key “LEScanWindowDiscovery” in group “Controller”
bluetoothd[1416]: src/main.c:parse_controller_config() Key file does not have key “LEScanIntervalAdvMonitor” in group “Controller”
bluetoothd[1416]: src/main.c:parse_controller_config() Key file does not have key “LEScanWindowAdvMonitor” in group “Controller”
bluetoothd[1416]: src/main.c:parse_controller_config() Key file does not have key “LEScanIntervalConnect” in group “Controller”
bluetoothd[1416]: src/main.c:parse_controller_config() Key file does not have key “LEScanWindowConnect” in group “Controller”
bluetoothd[1416]: src/main.c:parse_controller_config() Key file does not have key “LEMinConnectionInterval” in group “Controller”
bluetoothd[1416]: src/main.c:parse_controller_config() Key file does not have key “LEMaxConnectionInterval” in group “Controller”
bluetoothd[1416]: src/main.c:parse_controller_config() Key file does not have key “LEConnectionLatency” in group “Controller”
bluetoothd[1416]: src/main.c:parse_controller_config() Key file does not have key “LEConnectionSupervisionTimeout” in group “Controller”
bluetoothd[1416]: src/main.c:parse_controller_config() Key file does not have key “LEAutoconnecttimeout” in group “Controller”
systemd[1]: Started Bluetooth service.
bluetoothd[1416]: Starting SDP server
systemd[1]: Started Bluetooth service.
ssystemd[1]: Reached target Bluetooth.
bluetoothd[1416]: Bluetooth management interface 1.17 initialized
bluetoothd[1416]: Endpoint registered: sender=:1.52 path=/MediaEndpoint/A2DPSink/sbc
bluetoothd[1416]: Endpoint registered: sender=:1.52 path=/MediaEndpoint/A2DPSource/sbc

Before:
systemd[1]: Starting Bluetooth service...
bluetoothd[1747]: Bluetooth daemon 5.54
bluetoothd[1747]: Starting SDP server
bluetoothd[1747]: Bluetooth management interface 1.17 initialized
systemd[1]: Started Bluetooth service.
bluetoothd[1747]: Endpoint registered: sender=:1.52 path=/MediaEndpoint/A2DPSink/sbc
bluetoothd[1747]: Endpoint registered: sender=:1.52 path=/MediaEndpoint/A2DPSource/sbc

Meanwhile, function is OK, my bluetooth headset still works fine.

Analyzing /etc/bluetooth/main.conf as refered in RPM SPEC file as %{_sysconfdir}/bluetooth/*.conf :

In [Controller] section, there are these comments:

---BEGIN QUOTE-----

[Controller]
# The following values are used to load default adapter parameters.  BlueZ loads
# the values into the kernel before the adapter is powered if the kernel
# supports the MGMT_LOAD_DEFAULT_PARAMETERS command. If a value isn't provided,
# the kernel will be initialized to it's default value.  The actual value will
# vary based on the kernel version and thus aren't provided here.
# The Bluetooth Core Specification should be consulted for the meaning and valid
# domain of each of these values.

# BR/EDR Page scan activity configuration
#BRPageScanType=
#BRPageScanInterval=
#BRPageScanWindow=

# BR/EDR Inquiry scan activity configuration
#BRInquiryScanType=
#BRInquiryScanInterval=
#BRInquiryScanWindow=

# BR/EDR Link supervision timeout
#BRLinkSupervisionTimeout=

# BR/EDR Page Timeout
#BRPageTimeout=

# BR/EDR Sniff Intervals
#BRMinSniffInterval=
#BRMaxSniffInterval=

# LE advertisement interval (used for legacy advertisement interface only)
#LEMinAdvertisementInterval=
#LEMaxAdvertisementInterval=
#LEMultiAdvertisementRotationInterval=

# LE scanning parameters used for passive scanning supporting auto connect
# scenarios
#LEScanIntervalAutoConnect=
#LEScanWindowAutoConnect=

# LE scanning parameters used for passive scanning supporting wake from suspend
# scenarios
#LEScanIntervalSuspend=
#LEScanWindowSuspend=

# LE scanning parameters used for active scanning supporting discovery
# proceedure
#LEScanIntervalDiscovery=
#LEScanWindowDiscovery=

# LE scanning parameters used for passive scanning supporting the advertisement
# monitor Apis
#LEScanIntervalAdvMonitor=
#LEScanWindowAdvMonitor=

# LE scanning parameters used for connection establishment.
#LEScanIntervalConnect=
#LEScanWindowConnect=

# LE default connection parameters.  These values are superceeded by any
# specific values provided via the Load Connection Parameters interface
#LEMinConnectionInterval=
#LEMaxConnectionInterval=
#LEConnectionLatency=
#LEConnectionSupervisionTimeout=
#LEAutoconnecttimeout=

--- END QUOTE-----------

All these values are not set. Comment above explicitly says: "If a value isn't provided,
the kernel will be initialized to it's default value.  The actual value will
vary based on the kernel version and thus aren't provided here.
The Bluetooth Core Specification should be consulted for the meaning and valid
domain of each of these values."

So if there is no value set, Kernel should set his default value and daemon should not complain by spamming dmesg.

Why these values are not set by default in config file provided upstream?

See Mageia Cauldron Bugzilla report: https://bugs.mageia.org/show_bug.cgi?id=27314

**Comment by Vudentz** [comment]
This have been fixed upstream:

https://git.kernel.org/pub/scm/bluetooth/bluez.git/commit/?id=02e46e9df6b0d897e6ba67dc3ea18e5e9c510e44

**Comment by aureoud-fr85** [comment]
Thanks.
