### ISSUE TITLE
v5.1 card and 5.x headset connect over older non-LE protocol

### ISSUE THREAD

**Issue by OJFord** [bluez/bluez#52]
This is going to be a poor issue I'm afraid, since my knowledge is limited in this area, but I'm happy to provide whatever you can tell me is missing (or it may not be an issue with bluez).

I upgraded from a v2.1 to v5.1 Bluetooth adapter largely because the audio quality in HSP/HFP mode was so poor (A2DP ok). However, it didn't seem to make any difference, and I was suspicious of the (low-seeming) ~16.6KB/s up and down (~41KB/s up, 370B/s down in A2DP) reported in `blueman`.

`btmon` shows an `LE Extended Advertising Report` with `Primary PHY: LE 1M` (# 18) but then a non-LE connection (# 34):

<details>
<summary>btmon output (details dropdown)</summary>
<pre>
> HCI Event: LE Meta Event (0x3e) plen 55                  #18 [hci0] 19.772247
      LE Extended Advertising Report (0x0d)
        Num reports: 1
        Entry 0
          Event type: 0x001b
            Props: 0x001b
              Connectable
              Scannable
              Scan response
              Use legacy advertising PDUs
            Data status: [0;32mComplete[0m
          Legacy PDU Type: SCAN_RSP to an ADV_SCAN_IND (0x001b)
          Address type: Public (0x00)
          Address: 64:1C:AE:04:7D:6D (Samsung Electronics Co.,Ltd)
          Primary PHY: LE 1M
          Secondary PHY: No packets
          SID: no ADI field (0xff)
          TX power: 127 dBm
          RSSI: -73 dBm (0xb7)
          Periodic advertising invteral: 0.00 msec (0x0000)
          Direct address type: Public (0x00)
          Direct address: 00:00:00:00:00:00 (OUI 00-00-00)
          Data length: 0x1d
        1c 08 5b 54 56 5d 20 53 61 6d 73 75 6e 67 20 51  ..[TV] Samsung Q
        36 20 53 65 72 69 65 73 20 28 34 39 29           6 Series (49)   
@ MGMT Event: Device Found (0x0012) plen 74           {0x0001} [hci0] 19.772274
        LE Address: 64:1C:AE:04:7D:6D (Samsung Electronics Co.,Ltd)
        RSSI: -73 dBm (0xb7)
        Flags: 0x00000000
        Data length: 60
        Flags: 0x1a
          LE General Discoverable Mode
          Simultaneous LE and BR/EDR (Controller)
          Simultaneous LE and BR/EDR (Host)
        Company: Samsung Electronics Co. Ltd. (117)
          Data: 420401016f641cae047d6d661cae047d6c0bca0000000000
        Name (short): [TV] Samsung Q6 Series (49)
@ RAW Open: blueman-manager version 2.22                     {0x0002} 19.838483
@ RAW Close: blueman-manager                                 {0x0002} 19.838490
> HCI Event: LE Meta Event (0x3e) plen 43                  #19 [hci0] 19.970309
      LE Extended Advertising Report (0x0d)
        Num reports: 1
        Entry 0
          Event type: 0x0013
            Props: 0x0013
              Connectable
              Scannable
              Use legacy advertising PDUs
            Data status: [0;32mComplete[0m
          Legacy PDU Type: ADV_IND (0x0013)
          Address type: Random (0x01)
          Address: 73:CA:5D:70:5A:0D (Resolvable)
          Primary PHY: LE 1M
          Secondary PHY: No packets
          SID: no ADI field (0xff)
          TX power: 127 dBm
          RSSI: -85 dBm (0xab)
          Periodic advertising invteral: 0.00 msec (0x0000)
          Direct address type: Public (0x00)
          Direct address: 00:00:00:00:00:00 (OUI 00-00-00)
          Data length: 0x11
        02 01 1a 02 0a 08 0a ff 4c 00 10 05 61 1c ca 67  ........L...a..g
        57                                               W               
> HCI Event: LE Meta Event (0x3e) plen 26                  #20 [hci0] 19.971308
      LE Extended Advertising Report (0x0d)
        Num reports: 1
        Entry 0
          Event type: 0x001b
            Props: 0x001b
              Connectable
              Scannable
              Scan response
              Use legacy advertising PDUs
            Data status: [0;32mComplete[0m
          Legacy PDU Type: SCAN_RSP to an ADV_SCAN_IND (0x001b)
          Address type: Random (0x01)
          Address: 73:CA:5D:70:5A:0D (Resolvable)
          Primary PHY: LE 1M
          Secondary PHY: No packets
          SID: no ADI field (0xff)
          TX power: 127 dBm
          RSSI: -86 dBm (0xaa)
          Periodic advertising invteral: 0.00 msec (0x0000)
          Direct address type: Public (0x00)
          Direct address: 00:00:00:00:00:00 (OUI 00-00-00)
          Data length: 0x00
@ MGMT Event: Device Found (0x0012) plen 31           {0x0001} [hci0] 19.971340
        LE Address: 73:CA:5D:70:5A:0D (Resolvable)
        RSSI: -86 dBm (0xaa)
        Flags: 0x00000000
        Data length: 17
        Flags: 0x1a
          LE General Discoverable Mode
          Simultaneous LE and BR/EDR (Controller)
          Simultaneous LE and BR/EDR (Host)
        TX power: 8 dBm
        Company: Apple, Inc. (76)
          Type: Unknown (16)
          Data: 611cca6757
> HCI Event: Extended Inquiry Result (0x2f) plen 255       #21 [hci0] 20.025208
        Num responses: 1
        Address: 64:1C:AE:04:7D:6D (Samsung Electronics Co.,Ltd)
        Page scan repetition mode: R1 (0x01)
        Page period mode: P0 (0x00)
        Class: 0x0c043c
          Major class: Audio/Video (headset, speaker, stereo, video, vcr)
          Minor class: Video Display and Loudspeaker
          Rendering (Printing, Speaker)
          Capturing (Scanner, Microphone)
        Clock offset: 0x19f6
        RSSI: -86 dBm (0xaa)
        Device ID: Bluetooth SIG assigned (0x0001)
          Vendor: STABILO International (1256)
          Product: 0x8080
          Version: 0.0.0 (0x0000)
        Name (complete): [TV] Samsung Q6 Series (49)
        16-bit Service UUIDs (complete): 5 entries
          Audio Source (0x110a)
          Audio Sink (0x110b)
          A/V Remote Control Target (0x110c)
          A/V Remote Control (0x110e)
          PnP Information (0x1200)
        Company: Qualcomm (29)
          Data: 00014c
@ MGMT Event: Device Found (0x0012) plen 81           {0x0001} [hci0] 20.025223
        BR/EDR Address: 64:1C:AE:04:7D:6D (Samsung Electronics Co.,Ltd)
        RSSI: -86 dBm (0xaa)
        Flags: 0x00000000
        Data length: 67
        Device ID: Bluetooth SIG assigned (0x0001)
          Vendor: STABILO International (1256)
          Product: 0x8080
          Version: 0.0.0 (0x0000)
        Name (complete): [TV] Samsung Q6 Series (49)
        16-bit Service UUIDs (complete): 5 entries
          Audio Source (0x110a)
          Audio Sink (0x110b)
          A/V Remote Control Target (0x110c)
          A/V Remote Control (0x110e)
          PnP Information (0x1200)
        Company: Qualcomm (29)
          Data: 00014c
        Class: 0x0c043c
          Major class: Audio/Video (headset, speaker, stereo, video, vcr)
          Minor class: Video Display and Loudspeaker
          Rendering (Printing, Speaker)
          Capturing (Scanner, Microphone)
@ RAW Open: blueman-manager version 2.22                     {0x0002} 20.838806
@ RAW Close: blueman-manager                                 {0x0002} 20.838828
> HCI Event: LE Meta Event (0x3e) plen 57                  #22 [hci0] 20.990286
      LE Extended Advertising Report (0x0d)
        Num reports: 1
        Entry 0
          Event type: 0x0010
            Props: 0x0010
              Use legacy advertising PDUs
            Data status: [0;32mComplete[0m
          Legacy PDU Type: ADV_NONCONN_IND (0x0010)
          Address type: Random (0x01)
          Address: 21:74:80:01:6E:31 (Non-Resolvable)
          Primary PHY: LE 1M
          Secondary PHY: No packets
          SID: no ADI field (0xff)
          TX power: 127 dBm
          RSSI: -72 dBm (0xb8)
          Periodic advertising invteral: 0.00 msec (0x0000)
          Direct address type: Public (0x00)
          Direct address: 00:00:00:00:00:00 (OUI 00-00-00)
          Data length: 0x1f
        02 01 1a 03 03 6f fd 17 16 6f fd d2 50 c7 61 f3  .....o...o..P.a.
        3e 93 55 88 a4 8b 70 ea 1e 6d a0 eb 4f 23 69     >.U...p..m..O#i 
@ MGMT Event: Device Found (0x0012) plen 45           {0x0001} [hci0] 20.990328
        LE Address: 21:74:80:01:6E:31 (Non-Resolvable)
        RSSI: -72 dBm (0xb8)
        Flags: 0x00000004
          Not Connectable
        Data length: 31
        Flags: 0x1a
          LE General Discoverable Mode
          Simultaneous LE and BR/EDR (Controller)
          Simultaneous LE and BR/EDR (Host)
        16-bit Service UUIDs (complete): 1 entry
          Apple, Inc. (0xfd6f)
        Service Data (UUID 0xfd6f): d250c761f33e935588a48b70ea1e6da0eb4f2369
@ RAW Open: blueman-manager version 2.22                     {0x0002} 21.839886
@ RAW Close: blueman-manager                                 {0x0002} 21.839909
> HCI Event: LE Meta Event (0x3e) plen 54                  #23 [hci0] 22.168253
      LE Extended Advertising Report (0x0d)
        Num reports: 1
        Entry 0
          Event type: 0x0010
            Props: 0x0010
              Use legacy advertising PDUs
            Data status: [0;32mComplete[0m
          Legacy PDU Type: ADV_NONCONN_IND (0x0010)
          Address type: Public (0x00)
          Address: 00:7C:2D:E2:E9:F1 (Samsung Electronics Co.,Ltd)
          Primary PHY: LE 1M
          Secondary PHY: No packets
          SID: no ADI field (0xff)
          TX power: 127 dBm
          RSSI: -96 dBm (0xa0)
          Periodic advertising invteral: 0.00 msec (0x0000)
          Direct address type: Public (0x00)
          Direct address: 00:00:00:00:00:00 (OUI 00-00-00)
          Data length: 0x1c
        1b ff 75 00 42 04 01 80 60 00 7c 2d e2 e9 f1 02  ..u.B...`.|-....
        7c 2d e2 e9 f0 01 00 00 00 00 00 00              |-..........    
@ MGMT Event: Device Found (0x0012) plen 42           {0x0001} [hci0] 22.168307
        LE Address: 00:7C:2D:E2:E9:F1 (Samsung Electronics Co.,Ltd)
        RSSI: -96 dBm (0xa0)
        Flags: 0x00000004
          Not Connectable
        Data length: 28
        Company: Samsung Electronics Co. Ltd. (117)
          Data: 4204018060007c2de2e9f1027c2de2e9f001000000000000
> HCI Event: LE Meta Event (0x3e) plen 44                  #24 [hci0] 22.320251
      LE Extended Advertising Report (0x0d)
        Num reports: 1
        Entry 0
          Event type: 0x0013
            Props: 0x0013
              Connectable
              Scannable
              Use legacy advertising PDUs
            Data status: [0;32mComplete[0m
          Legacy PDU Type: ADV_IND (0x0013)
          Address type: Random (0x01)
          Address: 7B:A2:7C:31:F7:69 (Resolvable)
          Primary PHY: LE 1M
          Secondary PHY: No packets
          SID: no ADI field (0xff)
          TX power: 127 dBm
          RSSI: -77 dBm (0xb3)
          Periodic advertising invteral: 0.00 msec (0x0000)
          Direct address type: Public (0x00)
          Direct address: 00:00:00:00:00:00 (OUI 00-00-00)
          Data length: 0x12
        02 01 1a 02 0a 0c 0b ff 4c 00 10 06 41 1e 13 64  ........L...A..d
        1e 6e                                            .n              
> HCI Event: LE Meta Event (0x3e) plen 26                  #25 [hci0] 22.321268
      LE Extended Advertising Report (0x0d)
        Num reports: 1
        Entry 0
          Event type: 0x001b
            Props: 0x001b
              Connectable
              Scannable
              Scan response
              Use legacy advertising PDUs
            Data status: [0;32mComplete[0m
          Legacy PDU Type: SCAN_RSP to an ADV_SCAN_IND (0x001b)
          Address type: Random (0x01)
          Address: 7B:A2:7C:31:F7:69 (Resolvable)
          Primary PHY: LE 1M
          Secondary PHY: No packets
          SID: no ADI field (0xff)
          TX power: 127 dBm
          RSSI: -77 dBm (0xb3)
          Periodic advertising invteral: 0.00 msec (0x0000)
          Direct address type: Public (0x00)
          Direct address: 00:00:00:00:00:00 (OUI 00-00-00)
          Data length: 0x00
@ MGMT Event: Device Found (0x0012) plen 32           {0x0001} [hci0] 22.321347
        LE Address: 7B:A2:7C:31:F7:69 (Resolvable)
        RSSI: -77 dBm (0xb3)
        Flags: 0x00000000
        Data length: 18
        Flags: 0x1a
          LE General Discoverable Mode
          Simultaneous LE and BR/EDR (Controller)
          Simultaneous LE and BR/EDR (Host)
        TX power: 12 dBm
        Company: Apple, Inc. (76)
          Type: Unknown (16)
          Data: 411e13641e6e
> HCI Event: LE Meta Event (0x3e) plen 54                  #26 [hci0] 22.422254
      LE Extended Advertising Report (0x0d)
        Num reports: 1
        Entry 0
          Event type: 0x0012
            Props: 0x0012
              Scannable
              Use legacy advertising PDUs
            Data status: [0;32mComplete[0m
          Legacy PDU Type: ADV_SCAN_IND (0x0012)
          Address type: Random (0x01)
          Address: 6C:AC:AC:F6:06:36 (Resolvable)
          Primary PHY: LE 1M
          Secondary PHY: No packets
          SID: no ADI field (0xff)
          TX power: 127 dBm
          RSSI: -71 dBm (0xb9)
          Periodic advertising invteral: 0.00 msec (0x0000)
          Direct address type: Public (0x00)
          Direct address: 00:00:00:00:00:00 (OUI 00-00-00)
          Data length: 0x1c
        03 03 9f fe 17 16 9f fe 00 00 00 00 00 00 00 00  ................
        00 00 00 00 00 00 00 00 00 00 00 00              ............    
> HCI Event: LE Meta Event (0x3e) plen 36                  #27 [hci0] 22.423251
      LE Extended Advertising Report (0x0d)
        Num reports: 1
        Entry 0
          Event type: 0x001a
            Props: 0x001a
              Scannable
              Scan response
              Use legacy advertising PDUs
            Data status: [0;32mComplete[0m
          Legacy PDU Type: SCAN_RSP to an ADV_IND (0x001a)
          Address type: Random (0x01)
          Address: 6C:AC:AC:F6:06:36 (Resolvable)
          Primary PHY: LE 1M
          Secondary PHY: No packets
          SID: no ADI field (0xff)
          TX power: 127 dBm
          RSSI: -71 dBm (0xb9)
          Periodic advertising invteral: 0.00 msec (0x0000)
          Direct address type: Public (0x00)
          Direct address: 00:00:00:00:00:00 (OUI 00-00-00)
          Data length: 0x0a
        09 ff e0 00 01 69 ca 5c d8 a9                    .....i.\..      
@ MGMT Event: Device Found (0x0012) plen 52           {0x0001} [hci0] 22.423287
        LE Address: 6C:AC:AC:F6:06:36 (Resolvable)
        RSSI: -71 dBm (0xb9)
        Flags: 0x00000004
          Not Connectable
        Data length: 38
        16-bit Service UUIDs (complete): 1 entry
          Google (0xfe9f)
        Service Data (UUID 0xfe9f): 0000000000000000000000000000000000000000
        Company: Google (224)
          Data: 0169ca5cd8a9
> HCI Event: Extended Inquiry Result (0x2f) plen 255       #28 [hci0] 22.473242
        Num responses: 1
        Address: 00:25:BB:06:6D:62 (INNERINT Co., Ltd.)
        Page scan repetition mode: R1 (0x01)
        Page period mode: P0 (0x00)
        Class: 0x240418
          Major class: Audio/Video (headset, speaker, stereo, video, vcr)
          Minor class: Headphones
          Rendering (Printing, Speaker)
          Audio (Speaker, Microphone, Headset)
        Clock offset: 0x70c1
        RSSI: -59 dBm (0xc5)
        Device ID: Bluetooth SIG assigned (0x0001)
          Vendor: Cambridge Silicon Radio (10)
          Product: 0xffff
          Version: 255.15.15 (0xffff)
        TX power: 4 dBm
        16-bit Service UUIDs (partial): 7 entries
          Advanced Audio Distribution (0x110d)
          Audio Sink (0x110b)
          A/V Remote Control (0x110e)
          A/V Remote Control Controller (0x110f)
          Handsfree (0x111e)
          Headset (0x1108)
          Headset HS (0x1131)
        Name (complete): TAOTRONICS SoundElite 72
@ MGMT Event: Device Found (0x0012) plen 74           {0x0001} [hci0] 22.473317
        BR/EDR Address: 00:25:BB:06:6D:62 (INNERINT Co., Ltd.)
        RSSI: -59 dBm (0xc5)
        Flags: 0x00000000
        Data length: 60
        Device ID: Bluetooth SIG assigned (0x0001)
          Vendor: Cambridge Silicon Radio (10)
          Product: 0xffff
          Version: 255.15.15 (0xffff)
        TX power: 4 dBm
        16-bit Service UUIDs (partial): 7 entries
          Advanced Audio Distribution (0x110d)
          Audio Sink (0x110b)
          A/V Remote Control (0x110e)
          A/V Remote Control Controller (0x110f)
          Handsfree (0x111e)
          Headset (0x1108)
          Headset HS (0x1131)
        Name (complete): TAOTRONICS SoundElite 72
        Class: 0x240418
          Major class: Audio/Video (headset, speaker, stereo, video, vcr)
          Minor class: Headphones
          Rendering (Printing, Speaker)
          Audio (Speaker, Microphone, Headset)
> HCI Event: LE Meta Event (0x3e) plen 56                  #29 [hci0] 22.610252
      LE Extended Advertising Report (0x0d)
        Num reports: 1
        Entry 0
          Event type: 0x0013
            Props: 0x0013
              Connectable
              Scannable
              Use legacy advertising PDUs
            Data status: [0;32mComplete[0m
          Legacy PDU Type: ADV_IND (0x0013)
          Address type: Random (0x01)
          Address: 4E:E9:D4:CD:76:52 (Resolvable)
          Primary PHY: LE 1M
          Secondary PHY: No packets
          SID: no ADI field (0xff)
          TX power: 127 dBm
          RSSI: -93 dBm (0xa3)
          Periodic advertising invteral: 0.00 msec (0x0000)
          Direct address type: Public (0x00)
          Direct address: 00:00:00:00:00:00 (OUI 00-00-00)
          Data length: 0x1e
        02 01 02 13 ff ff ff 63 64 35 30 35 64 30 61 64  .......cd505d0ad
        64 33 64 65 61 33 30 02 0a f1 03 03 56 34        d3dea30.....V4  
> HCI Event: LE Meta Event (0x3e) plen 34                  #30 [hci0] 22.611235
      LE Extended Advertising Report (0x0d)
        Num reports: 1
        Entry 0
          Event type: 0x001b
            Props: 0x001b
              Connectable
              Scannable
              Scan response
              Use legacy advertising PDUs
            Data status: [0;32mComplete[0m
          Legacy PDU Type: SCAN_RSP to an ADV_SCAN_IND (0x001b)
          Address type: Random (0x01)
          Address: 4E:E9:D4:CD:76:52 (Resolvable)
          Primary PHY: LE 1M
          Secondary PHY: No packets
          SID: no ADI field (0xff)
          TX power: 127 dBm
          RSSI: -94 dBm (0xa2)
          Periodic advertising invteral: 0.00 msec (0x0000)
          Direct address type: Public (0x00)
          Direct address: 00:00:00:00:00:00 (OUI 00-00-00)
          Data length: 0x08
        07 09 53 48 49 45 4c 44                          ..SHIELD        
@ MGMT Event: Device Found (0x0012) plen 52           {0x0001} [hci0] 22.611264
        LE Address: 4E:E9:D4:CD:76:52 (Resolvable)
        RSSI: -94 dBm (0xa2)
        Flags: 0x00000000
        Data length: 38
        Flags: 0x02
          LE General Discoverable Mode
        Company: internal use (65535)
          Data: 63643530356430616464336465613330
        TX power: -15 dBm
        16-bit Service UUIDs (complete): 1 entry
          Unknown (0x3456)
        Name (complete): SHIELD
@ RAW Open: blueman-manager version 2.22                     {0x0002} 22.840784
@ RAW Close: blueman-manager                                 {0x0002} 22.840806
> HCI Event: LE Meta Event (0x3e) plen 44                  #31 [hci0] 23.103250
      LE Extended Advertising Report (0x0d)
        Num reports: 1
        Entry 0
          Event type: 0x0013
            Props: 0x0013
              Connectable
              Scannable
              Use legacy advertising PDUs
            Data status: [0;32mComplete[0m
          Legacy PDU Type: ADV_IND (0x0013)
          Address type: Random (0x01)
          Address: 62:06:CB:32:EC:15 (Resolvable)
          Primary PHY: LE 1M
          Secondary PHY: No packets
          SID: no ADI field (0xff)
          TX power: 127 dBm
          RSSI: -84 dBm (0xac)
          Periodic advertising invteral: 0.00 msec (0x0000)
          Direct address type: Public (0x00)
          Direct address: 00:00:00:00:00:00 (OUI 00-00-00)
          Data length: 0x12
        02 01 1a 02 0a 0c 0b ff 4c 00 10 06 46 1e 16 df  ........L...F...
        8a 70                                            .p              
> HCI Event: LE Meta Event (0x3e) plen 26                  #32 [hci0] 23.104231
      LE Extended Advertising Report (0x0d)
        Num reports: 1
        Entry 0
          Event type: 0x001b
            Props: 0x001b
              Connectable
              Scannable
              Scan response
              Use legacy advertising PDUs
            Data status: [0;32mComplete[0m
          Legacy PDU Type: SCAN_RSP to an ADV_SCAN_IND (0x001b)
          Address type: Random (0x01)
          Address: 62:06:CB:32:EC:15 (Resolvable)
          Primary PHY: LE 1M
          Secondary PHY: No packets
          SID: no ADI field (0xff)
          TX power: 127 dBm
          RSSI: -83 dBm (0xad)
          Periodic advertising invteral: 0.00 msec (0x0000)
          Direct address type: Public (0x00)
          Direct address: 00:00:00:00:00:00 (OUI 00-00-00)
          Data length: 0x00
@ MGMT Event: Device Found (0x0012) plen 32           {0x0001} [hci0] 23.104269
        LE Address: 62:06:CB:32:EC:15 (Resolvable)
        RSSI: -83 dBm (0xad)
        Flags: 0x00000000
        Data length: 18
        Flags: 0x1a
          LE General Discoverable Mode
          Simultaneous LE and BR/EDR (Controller)
          Simultaneous LE and BR/EDR (Host)
        TX power: 12 dBm
        Company: Apple, Inc. (76)
          Type: Unknown (16)
          Data: 461e16df8a70
> HCI Event: LE Meta Event (0x3e) plen 57                  #33 [hci0] 23.108257
      LE Extended Advertising Report (0x0d)
        Num reports: 1
        Entry 0
          Event type: 0x0010
            Props: 0x0010
              Use legacy advertising PDUs
            Data status: [0;32mComplete[0m
          Legacy PDU Type: ADV_NONCONN_IND (0x0010)
          Address type: Random (0x01)
          Address: 38:90:97:52:49:1D (Non-Resolvable)
          Primary PHY: LE 1M
          Secondary PHY: No packets
          SID: no ADI field (0xff)
          TX power: 127 dBm
          RSSI: -83 dBm (0xad)
          Periodic advertising invteral: 0.00 msec (0x0000)
          Direct address type: Public (0x00)
          Direct address: 00:00:00:00:00:00 (OUI 00-00-00)
          Data length: 0x1f
        02 01 1a 03 03 6f fd 17 16 6f fd a8 f4 78 44 94  .....o...o...xD.
        a0 42 c5 09 04 c9 b6 f8 d4 4d 67 ae 16 00 ff     .B.......Mg.... 
@ MGMT Event: Device Found (0x0012) plen 45           {0x0001} [hci0] 23.108324
        LE Address: 38:90:97:52:49:1D (Non-Resolvable)
        RSSI: -83 dBm (0xad)
        Flags: 0x00000004
          Not Connectable
        Data length: 31
        Flags: 0x1a
          LE General Discoverable Mode
          Simultaneous LE and BR/EDR (Controller)
          Simultaneous LE and BR/EDR (Host)
        16-bit Service UUIDs (complete): 1 entry
          Apple, Inc. (0xfd6f)
        Service Data (UUID 0xfd6f): a8f4784494a042c50904c9b6f8d44d67ae1600ff
> HCI Event: LE Meta Event (0x3e) plen 57                  #34 [hci0] 23.176254
      LE Extended Advertising Report (0x0d)
        Num reports: 1
        Entry 0
          Event type: 0x0010
            Props: 0x0010
              Use legacy advertising PDUs
            Data status: [0;32mComplete[0m
          Legacy PDU Type: ADV_NONCONN_IND (0x0010)
          Address type: Random (0x01)
          Address: 15:E9:10:B9:96:3C (Non-Resolvable)
          Primary PHY: LE 1M
          Secondary PHY: No packets
          SID: no ADI field (0xff)
          TX power: 127 dBm
          RSSI: -90 dBm (0xa6)
          Periodic advertising invteral: 0.00 msec (0x0000)
          Direct address type: Public (0x00)
          Direct address: 00:00:00:00:00:00 (OUI 00-00-00)
          Data length: 0x1f
        1e ff 06 00 01 09 20 02 90 f0 98 f7 32 05 b4 a2  ...... .....2...
        83 8f b1 5f fe 05 9e 63 ad 89 00 6b eb 32 0d     ..._...c...k.2. 
</pre></details>

Apologies again if this is not a `bluez` issue, but I would appreciate even a redirection!

**Comment by Vudentz** [comment]
HSP/HFP are BR/EDR only, so they cannot really use LE.
