### ISSUE TITLE
Profile1 interface method RequestDisconnection() is not called when the client disconnects

### ISSUE THREAD

**Issue by SwordTechCorp** [bluez/bluez#522]
[BlueZ 5.55]
I tried the test file [test/test_profile](https://github.com/bluez/bluez/blob/master/test/test-profile) on Raspbian with the following arguments
`./test-profile -u 00001101-0000-1000-8000-00805f9b34fb -s -n fstest -C 8 -S 1101`

As I connect to the Raspberry Pi with my Android device, NewConnection() is called, which is great. The connection is established. 

However, if I disconnect it on the Android side, the RequestDisconnection() is not called. 

When I check the sockets by the following command
` sudo cat /sys/kernel/debug/bluetooth/rfcomm`
The result is 
`b9:27:eb:73:67:0a 34:7A:46:c4:81:5e 9 8`
`b9:27:eb:73:67:0a 00:00:00:00:00:00 4 8`

**Comment by Vudentz** [comment]
@SwordTechCorp if it is request by the remote end you will need to monitor the socket passed via NewConnection for HUP event, RequestDisconnection is only called if the stack initiates the disconnection so you can cleanup before it is terminated.
