### ISSUE TITLE
[5.68] Bluetooth works but full of junk in journalctl

### ISSUE THREAD

**Issue by Freyon77** [bluez/bluez#550]
I checked myself these new versions of bluez.
A lot of spam appeared.

src/adapter.c:reset_adv_monitors_complete() 
Failed to reset Adv monitors: Failed (0x03)

Failed to add UUID: Failed (0x03)

Failed to add UUID: Failed (0x03)

Failed to add UUID: Failed (0x03)

Arch Linux

Intel 3165 Dual Band Wireless-AC Plus Bluetooth (rev 99)

**Comment by Freyon77** [comment]
It dissappeared after reboot

**Comment by Freyon77** [comment]
Steps to reproduce

Boot Arch Linux installation medium

Mount your drive

Arch-chroot /mnt

Su (your name)

Logout

(You will get an error message saying you should type "exit")

Exit

Exit

Reboot

Now you will see mentioned errors in journalctl

**Comment by Freyon77** [comment]
Closing - kernel issue

**Comment by Crandel** [comment]
Can you share this kernel issue, please?

**Comment by Freyon77** [comment]
> @Freyon77 Can you share this kernel issue, please?

No, i have made research again, and on driver site it says my device will no longer be supported by latest driver
