### ISSUE TITLE
Running bluez 5.68 on Raspbian Buster with an older LIBC6 and GLIBC

### ISSUE THREAD

**Issue by skast96** [bluez/bluez#564]
It is possible to compile the bluez package with an older version of LIBC6, however is it clever to do that or should i consider a dist-upgrade because the older libc6 is missing some edge cases where the bluez stack is missing shared files?

Edit: I am asking because the newer versions of bluez in Debain bookworm etc. need a newer libc6 version. Is that because the system only provides a newer one or is it because bluez needs a newer libc6 version

**Comment by Vudentz** [comment]
@skast96 don't think we added any new dependencies, so it is worth checking if it compiles with older libc then I assume you should be fine.

**Comment by skast96** [comment]
@Vudentz thank you for your answer it worked installing bluez. However I need a debian package to make the installation process as light as possible do you guys have a script that builds a debian file out of the compiled bluez folder or is this managed by debian itself ?
