### ISSUE TITLE
SMP timeout leading disconnection with Android 13

### ISSUE THREAD

**Issue by nitin-rjadhav** [bluez/bluez#567]
### **Description:**
Advertise from : Mobile Phone
Scan from : Linux Bluez DUT (bluetoothctl)

Android 13 phones are connected as master during pairing process, and this conflicts with the keys exchange process that leads to SMP timeout. In comparison, Android 12 or iPhone act as slaves during the pairing process; hence the issue is not observed with them.

As per Bluetooth specs, an Initiator(master) sends smp pairing request command (in which keys that the initiator requests to share and keys it demands from the responder/slave are mentioned).
![image](https://github.com/bluez/bluez/assets/122077213/06e51d36-ba25-430c-b9ad-836a997b3b5e)

In return, the responder sends smp pairing response (in which it sends keys that shall be shared by the initiator and keys which the responder shall share).
![image](https://github.com/bluez/bluez/assets/122077213/a4282d5d-fe8e-4d9d-96a0-5d88b9be1a9d)

According to the specs, after the pairing response is sent, the responder/slave shall send its keys first (whichever is mentioned in the responder key distribution field of the pairing response).

Till android 12, all phones were connecting as slaves when the connection was initiated from the DUT, and the link was successful as phones were not changing their roles to master until all the SMP commands and key exchanges were complete. Starting from Android 13, phones sent role change orders after the DUT initiated the connection and became master.

### **Analysis and Fix**

**Analysis**
- All SMP-related tasks (handling SMP commands and keys generation/distribution) are handled in the Linux kernel smp.c file.
- In which it is found that code only checks whether the connection is initiated from its side (hcon->out == 1), or it is an incoming connection(hcon->out == 0) from the other side. 
- As the connection is initiated from the DUT side, it expects itself as master as there is no check for its role, and it waits for keys from the phone despite being in a slave role, and an SMP timeout happens.

Please find the code screenshot for reference: - (linux-kernel/net/bluetooth/smp.c)
![image](https://github.com/bluez/bluez/assets/122077213/7f0d21a1-c788-4c4c-b3f8-c101ad8f90b0)

**Fix:**
After putting a check for the role, the connection is maintained and keys are appropriately distributed according to specs (checked with pixel 7 phones), and the connection is maintained.
![image](https://github.com/bluez/bluez/assets/122077213/1fa171b6-7b34-4d29-a620-94eb180c7d33)

### **Consequence of fix:**
On Samsung phones with Android 13, we are facing issues during first-time connection, even with this patch. Later, the connection is sustained.

**Comment by Vudentz** [comment]
From the looks of it we were assuming hcon->out to mean central, but the SMP never says the central to correspond to initiator:

BLUETOOTH CORE SPECIFICATION Version 5.3 | Vol 3, Part H
page 1557:

Figure 2.1: LE pairing phases

So we need to check who actually sends the Pairing Request and properly mark is as iniatiator, that said it is probably recommended that only one side start the pairing procedure in which case the central probably needs to have priority over this, so when we act as peripheral we shall just send a Security_Request.

@NJNXP Can you please include the HCI/btmon traces as well?

**Comment by NJNXP** [comment]
Hello Luiz,

PFA the btmon logs for the issue.

For quick reference following our log analysis:

Initiated connection from Bluez to Android 13 Phone. As we can see the Android 13 changes its role to Master after connection.
![image](https://github.com/bluez/bluez/assets/122077213/5bdfd8dc-14d1-4097-a9bb-417f8d3dd91f)

As Android 13 is Master hence it will send Pairing request.
![image](https://github.com/bluez/bluez/assets/122077213/f4e2ccf8-f5db-4e40-ab1b-c49e5b081b1d)

- All SMP-related tasks (handling SMP commands and keys generation/distribution) are handled in the Linux kernel smp.c file 
- In which it is found that code only checks whether the connection is initiated from its side (hcon->out == 1), or it is an incoming connection(hcon->out == 0) from the other side. 
- As the connection is initiated from the Bluez side, it expects the keys  to be sent from the phone side.
- Whereas Android 13 is Master and is initiating Pairing request hence it also waits for Keys from Bluez side.  According to the specs, after the pairing response is sent, the responder/slave shall send its keys first (whichever is mentioned in the responder key distribution field of the pairing response).

This causes SMP Timeout issue and device get disconnected, and Phone removes the device from its paired list.
![image](https://github.com/bluez/bluez/assets/122077213/f75f2818-8c4a-4fc7-a1e9-9477498a57cd)

Thanks,
Warm Regards,
Nitin Jadhav

[Pixel7_with_bluez_5-66.txt](https://github.com/bluez/bluez/files/12248191/Pixel7_with_bluez_5-66.txt)

**Comment by NJNXP** [comment]
Hello @Vudentz,
In reference to the previous mentioned logs can you please further guide on this issue. 

Thanks in advance.

Warm Regards
Nitin Jadhav

**Comment by Vudentz** [comment]
@NJNXP have a look if the patch above fixes the problem, we may need to double check if there isn't any test on SMP testing that affects this change before we merge it though.

**Comment by purendra-singh** [comment]
Hi @Vudentz,

I tested the changes done and following are the observations:- 

1. Pixel Android 14:-  
a. Without fix, issue was seen on this phone too and behavior was same as Android 13, keys were not getting exchanged.
b. With fix, issue was not seen and all the keys during SMP pairing procedure were exchanged.

                                   
2. Iphone 14:-    Issue wasn't seen with or without fix.

3. Samsung S20 FE Android 13:-
a. Without fix, issue was seen with this phone, keys were not getting exchanged.
b. With Fix, pairing is done, while connect command we are getting error as "Failed to connect: org.bluez.Error.Failed br-connection-create-socket" and then connection fails.
c. We get connect request then from phone side and popup to Authorize service in bluetooth and when we authorize the service connection persists.
                                   
 Attaching logs for all three devices which contains bluetoothctl, bluetoothd and btmon.
 
 Thanks,
 Purendra Singh                                      
                                       
                                           
[With_Luiz_Patch.zip](https://github.com/bluez/bluez/files/12548284/With_Luiz_Patch.zip)

**Comment by Vudentz** [comment]
@purendra-singh thanks for testing, we may need to run SMP PTS tests just to be safe, can you do that?

**Comment by purendra-singh** [comment]
Hi @Vudentz,

Currently dont have compatible dongle to perform the SMP PTS test. 

Could you please provide us the link to the dongle which is used to do the PTS test for BREDR, so that we can procure it and use it future test cases if required.

Thanks,
Purendra Singh

**Comment by sameerfeb05** [comment]
@Vudentz I still don't see this change is upstreamed. Any reason why its not upstreamed?

**Comment by Vudentz** [comment]
> @Vudentz I still don't see this change is upstreamed. Any reason why its not upstreamed?

We need to confirm it doesn't break qualification.

**Comment by sameerfeb05** [comment]
@Vudentz  We have executed SMP PTS tests, all tests have passed with above change. We also observe this below

**b. With Fix, pairing is done, while connect command we are getting error as "Failed to connect: org.bluez.Error.Failed br-connection-create-socket" and then connection fails.** 

In above case remote is disconnecting all profiles so connect dbus method returning above error, after that remote is again connecting, so functionality is working fine.

**SM.TS.p24**

**Test Case ID**
SM/CEN/SCJW/BV-01-C
SM/PER/PKE/BV-02-C
SM/PER/PKE/BI-03-C
SM/CEN/SCPK/BI-02-C
SM/PER/JW/BI-02-C
SM/PER/KDU/BV-02-C
SM/CEN/EKS/BI-01-C
SM/CEN/EKS/BV-01-C
SM/CEN/PKE/BV-04-C
SM/CEN/JW/BV-05-C
SM/CEN/JW/BI-01-C
SM/CEN/JW/BI-04-C
SM/CEN/SCPK/BV-04-C
SM/PER/OOB/BV-08-C
SM/CEN/OOB/BV-05-C
SM/CEN/SIP/BV-02-C
SM/PER/PKE/BV-05-C
SM/CEN/KDU/BV-05-C
SM/CEN/PROT/BV-01-C
SM/PER/EKS/BV-02-C
SM/PER/EKS/BI-02-C
SM/PER/PROT/BV-02-C
SM/PER/KDU/BV-01-C
SM/PER/SCPK/BI-03-C
SM/PER/SCPK/BI-04-C
SM/PER/KDU/BI-03-C
SM/CEN/KDU/BV-06-C
SM/CEN/SCPK/BV-01-C
SM/PER/SCJW/BV-03-C
SM/CEN/PKE/BI-02-C
SM/CEN/PKE/BV-01-C
SM/CEN/PKE/BI-01-C
SM/PER/KDU/BV-07-C
SM/PER/SCPK/BV-02-C
SM/PER/SCPK/BV-03-C
SM/PER/SCJW/BV-02-C
SM/PER/KDU/BV-08-C
SM/PER/SCJW/BI-02-C
SM/PER/JW/BI-03-C
SM/PER/JW/BV-02-C
SM/CEN/OOB/BV-07-C
SM/CEN/KDU/BV-10-C
SM/CEN/SCJW/BV-04-C
SM/PER/KDU/BI-01-C
SM/CEN/SCJW/BI-01-C
SM/CEN/SCPK/BI-01-C
SM/CEN/KDU/BI-01-C
SM/PER/KDU/BI-02-C
SM/PER/OOB/BV-06-C

**Comment by Vudentz** [comment]
> @Vudentz We have executed SMP PTS tests, all tests have passed with above change. We also observe this below
> 
> **b. With Fix, pairing is done, while connect command we are getting error as "Failed to connect: org.bluez.Error.Failed br-connection-create-socket" and then connection fails.**
> 
> In above case remote is disconnecting all profiles so connect dbus method returning above error, after that remote is again connecting, so functionality is working fine.
> 
> **SM.TS.p24**
> 
> **Test Case ID** SM/CEN/SCJW/BV-01-C SM/PER/PKE/BV-02-C SM/PER/PKE/BI-03-C SM/CEN/SCPK/BI-02-C SM/PER/JW/BI-02-C SM/PER/KDU/BV-02-C SM/CEN/EKS/BI-01-C SM/CEN/EKS/BV-01-C SM/CEN/PKE/BV-04-C SM/CEN/JW/BV-05-C SM/CEN/JW/BI-01-C SM/CEN/JW/BI-04-C SM/CEN/SCPK/BV-04-C SM/PER/OOB/BV-08-C SM/CEN/OOB/BV-05-C SM/CEN/SIP/BV-02-C SM/PER/PKE/BV-05-C SM/CEN/KDU/BV-05-C SM/CEN/PROT/BV-01-C SM/PER/EKS/BV-02-C SM/PER/EKS/BI-02-C SM/PER/PROT/BV-02-C SM/PER/KDU/BV-01-C SM/PER/SCPK/BI-03-C SM/PER/SCPK/BI-04-C SM/PER/KDU/BI-03-C SM/CEN/KDU/BV-06-C SM/CEN/SCPK/BV-01-C SM/PER/SCJW/BV-03-C SM/CEN/PKE/BI-02-C SM/CEN/PKE/BV-01-C SM/CEN/PKE/BI-01-C SM/PER/KDU/BV-07-C SM/PER/SCPK/BV-02-C SM/PER/SCPK/BV-03-C SM/PER/SCJW/BV-02-C SM/PER/KDU/BV-08-C SM/PER/SCJW/BI-02-C SM/PER/JW/BI-03-C SM/PER/JW/BV-02-C SM/CEN/OOB/BV-07-C SM/CEN/KDU/BV-10-C SM/CEN/SCJW/BV-04-C SM/PER/KDU/BI-01-C SM/CEN/SCJW/BI-01-C SM/CEN/SCPK/BI-01-C SM/CEN/KDU/BI-01-C SM/PER/KDU/BI-02-C SM/PER/OOB/BV-06-C

Thanks for the quick testing, I will resend it to the list just to make sure it passes our tests.

**Comment by Vudentz** [comment]
https://patchwork.kernel.org/project/bluetooth/patch/20240813144559.529786-1-luiz.dentz@gmail.com/

Please add the Tested-By:

https://www.kernel.org/doc/html/latest/process/submitting-patches.html#using-reported-by-tested-by-reviewed-by-suggested-by-and-fixes

**Comment by sameerfeb05** [comment]
> https://patchwork.kernel.org/project/bluetooth/patch/20240813144559.529786-1-luiz.dentz@gmail.com/
> 
> Please add the Tested-By:
> 
> https://www.kernel.org/doc/html/latest/process/submitting-patches.html#using-reported-by-tested-by-reviewed-by-suggested-by-and-fixes

I am not aware of how to edit commit message to add Tested-By: in above link mentioned (patchwork.kernel.org).

Do i need to prepare patch by modifying commit message by adding Tested-By: , then need to send it to linux-kernel@vger.kernel.org ?

**Comment by Vudentz** [comment]
@sameerfeb05 just respond to the email thread adding the Tested-by, patchwork will do the rest.

**Comment by VinitMehta-NXP** [comment]
Hi @Vudentz ,

If this PR is already merged and nothing is pending than can we please close this issue?
We run into same issue and need to use this ticket for reference.

Regards,
Vinit
