### ISSUE TITLE
Memory leak in 'proxy_write_value' function

### ISSUE THREAD

**Issue by JoraGevorgyan** [bluez/bluez#587]
The memory leak is reported by a static analyzer tool developed at [CAST](https://www.linkedin.com/company/cast-center)
Specifically, memory is allocated in [here](https://github.com/bluez/bluez/blob/6a8f7c55dfdfed8136ba8b417d0d8ee45181001a/client/gatt.c#L2421) and it may be left w/o free in [here](https://github.com/bluez/bluez/blob/6a8f7c55dfdfed8136ba8b417d0d8ee45181001a/client/gatt.c#L2427)

**Comment by Vudentz** [comment]
It is freed on:

https://github.com/bluez/bluez/blob/6a8f7c55dfdfed8136ba8b417d0d8ee45181001a/client/gatt.c#L2411
