### ISSUE TITLE
Memory leak in 'ping' function

### ISSUE THREAD

**Issue by JoraGevorgyan** [bluez/bluez#589]
The memory leak is reported by a static analyzer tool developed at [CAST](https://www.linkedin.com/company/cast-center)
Specifically, memory is allocated in [here](https://github.com/bluez/bluez/blob/6a8f7c55dfdfed8136ba8b417d0d8ee45181001a/tools/l2ping.c#L75) (send_buf and recv_buf) and the program may exit w/o free if it fails to [create a socket](https://github.com/bluez/bluez/blob/6a8f7c55dfdfed8136ba8b417d0d8ee45181001a/tools/l2ping.c#L83C2-L83C2)

**Comment by Vudentz** [comment]
@JoraGevorgyan usually we don't care about memory leaks if the tool just exits in the process since the kernel will really all resources associated with the process anyway.
