### ISSUE TITLE
Does bluez support Windows 11?

### ISSUE THREAD

**Issue by snowuyl** [bluez/bluez#591]
I would like to develop Bluetooth applications on Windows 11. Does bluez support it?

**Comment by Vudentz** [comment]
@snowuyl BlueZ is Linux only, you may need to rely on toolkits such as QT, etc, that offers cross-platform support if you want to target multiple environments.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/bluez/bluez/issues/591#issue-1874565626

@snowuyl, probably better to ask questions at https://github.com/orgs/bluez/discussions/new?category=q-a in the future.
