### ISSUE TITLE
Bluetooth keyboard/mouse relay

### ISSUE THREAD

**Issue by Raraph84** [bluez/bluez#596]
Hello,

I'm currently working on a project where I aim to use a Raspberry Pi 4 as a Bluetooth relay for a keyboard and mouse. The primary goal of this project is to intercept mouse movements from a connected Bluetooth keyboard/mouse and relay them to another device while allowing the keyboard to function normally.

Simultaneously, I also want to capture keyboard events using the evtest tool on the Raspberry Pi 4.

I'd like to know if it's possible with BlueZ, and if so, what steps I should follow to implement it.

Additionally, I haven't been able to find a Discord to discuss this project, which is why I'm asking this question here. If anyone can direct me to a community or resource where I can get more information, it would be greatly appreciated.

Thank you to everyone who can provide information or guidance on realizing this project! 🙏

**Comment by Vudentz** [comment]
@Raraph84 you can contact us via slack or mailing list: http://www.bluez.org/contact/ as for acting as a relay, if depends on what sort of relay you want to do, there is some support for cloning GATT attributes though:

[bluetooth]# gatt.clone --help
Clone a device or attribute
Usage:
	 clone [dev/attribute/UUID]

That said it only clones the attributes that are not handled by bluetoothd, for instance HoG attributes are currently being handle by the input plugin so you would have to disable that, then once you clone these attributes would appear in the adapter database to a third device and the procedures would be relayed automatically by bluetoothctl.
