### ISSUE TITLE
pybluez erorr

### ISSUE THREAD

**Issue by Pataskralik** [bluez/bluez#613]
Hello, does anyone have any advice on what to do with this error?
PS C:\Users\patrm\Desktop\work> pip install pybluez
Collecting pybluez
  Using cached PyBluez-0.23.tar.gz (97 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in PyBluez setup command: use_2to3 is invalid.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
![image](https://github.com/bluez/bluez/assets/144142294/3a314d0c-4829-4072-98b7-d31b125cd81c)

**Comment by pv** [comment]
Probably should be asked at https://github.com/pybluez/pybluez, not here
