### ISSUE TITLE
BlueZ 5.71 is missing and solve vulnerabilities

### ISSUE THREAD

**Issue by Neustradamus** [bluez/bluez#681]
Dear @bluez team,

5.71 is missing:
- https://github.com/bluez/bluez/releases

Can you look the problem?

5.70 is not secure, vulnerabilities.

**Comment by Vudentz** [comment]
Fixed https://github.com/bluez/bluez/releases/tag/5.71

**Comment by Neustradamus** [comment]
@Vudentz: Thanks!
