### ISSUE TITLE
Bluetooth PBAP Client PTS test[PBAP/PCE/SSM/BV-06-C] for obex authentication is failing

### ISSUE THREAD

**Issue by sanchipsync** [bluez/bluez#729]
The Bluetooth PBAP Client  PTS test - PBAP/PCE/SSM/BV-06-C for obex authentication is failing with message "Wrong Authentication Response received". 

Bluez Version: 5.55

The test description is given below.
"Verify that the PCE responds properly to an authentication requests from the PSE at the time of PBAP session initiation".

Obex connection is initiated from the PCE using below command.
#obexctl
[NEW] Client /org/bluez/obex 
[obex]# connect 00:1B:XX:XX:XX:XX   0000112f-0000-1000-8000-00805f9b34fb
Attempting to connect to 00:1B:DC:F4:B0:4C
Failed to connect: org.bluez.obex.Error.Failed                                 

The btmon dump for the above test is given below.

Bluetooth monitor ver 5.55
= Note: Linux version 5.4.159-tcc (aarch64)                            0.972899
= Note: Bluetooth subsystem version 2.22                               0.972904
= New Index: 54:F8:2A:9A:B2:70 (Primary,UART,hci0)              [hci0] 0.972906
= Open Index: 54:F8:2A:9A:B2:70                                 [hci0] 0.972907
= Index Info: 54:F8:2A:9A:B2.. (Marvell Technology Group Ltd.)  [hci0] 0.972909
@ MGMT Open: bluetoothd (privileged) version 1.14             {0x0001} 0.972911
< HCI Command: Create Connection (0x01|0x0005) plen 13      #1 [hci0] 22.089025
        Address: 00:1B:DC:F4:B0:4C (OUI 00-1B-DC)
        Packet type: 0xcc18
          DM1 may be used
          DH1 may be used
          DM3 may be used
          DH3 may be used
          DM5 may be used
          DH5 may be used
        Page scan repetition mode: R2 (0x02)
        Page scan mode: Mandatory (0x00)
        Clock offset: 0x0000
        Role switch: Allow slave (0x01)
> HCI Event: Command Status (0x0f) plen 4                   #2 [hci0] 22.090330
      Create Connection (0x01|0x0005) ncmd 1
        Status: Success (0x00)
> HCI Event: Connect Complete (0x03) plen 11                #3 [hci0] 24.930608
        Status: Success (0x00)
        Handle: 1
        Address: 00:1B:DC:F4:B0:4C (OUI 00-1B-DC)
        Link type: ACL (0x01)
        Encryption: Disabled (0x00)
< HCI Command: Read Remote Supporte.. (0x01|0x001b) plen 2  #4 [hci0] 24.930757
        Handle: 1
> HCI Event: Command Status (0x0f) plen 4                   #5 [hci0] 24.932937
      Read Remote Supported Features (0x01|0x001b) ncmd 1
        Status: Success (0x00)
> HCI Event: Max Slots Change (0x1b) plen 3                 #6 [hci0] 24.955827
        Handle: 1
        Max slots: 5
> HCI Event: Read Remote Supported Features (0x0b) plen 11  #7 [hci0] 24.959054
        Status: Success (0x00)
        Handle: 1
        Features: 0xff 0xff 0x8f 0x7e 0xd8 0x1f 0x5b 0x87
          3 slot packets
          5 slot packets
          Encryption
          Slot offset
          Timing accuracy
          Role switch
          Hold mode
          Sniff mode
          Park state
          Power control requests
          Channel quality driven data rate (CQDDR)
          SCO link
          HV2 packets
          HV3 packets
          u-law log synchronous data
          A-law log synchronous data
          CVSD synchronous data
          Paging parameter negotiation
          Power control
          Transparent synchronous data
          Broadcast Encryption
          Enhanced Data Rate ACL 2 Mbps mode
          Enhanced Data Rate ACL 3 Mbps mode
          Enhanced inquiry scan
          Interlaced inquiry scan
          Interlaced page scan
          RSSI with inquiry results
          AFH capable slave
          AFH classification slave
          LE Supported (Controller)
          3-slot Enhanced Data Rate ACL packets
          5-slot Enhanced Data Rate ACL packets
          Sniff subrating
          Pause encryption
          AFH capable master
          AFH classification master
          Extended Inquiry Response
          Simultaneous LE and BR/EDR (Controller)
          Secure Simple Pairing
          Encapsulated PDU
          Non-flushable Packet Boundary Flag
          Link Supervision Timeout Changed Event
          Inquiry TX Power Level
          Enhanced Power Control
          Extended features
< HCI Command: Read Remote Extended.. (0x01|0x001c) plen 3  #8 [hci0] 24.959086
        Handle: 1
        Page: 1
> HCI Event: Page Scan Repetition Mode Cha.. (0x20) plen 7  #9 [hci0] 24.959335
        Address: 00:1B:DC:F4:B0:4C (OUI 00-1B-DC)
        Page scan repetition mode: R1 (0x01)
> HCI Event: Command Status (0x0f) plen 4                  #10 [hci0] 24.959769
      Read Remote Extended Features (0x01|0x001c) ncmd 1
        Status: Success (0x00)
> HCI Event: Read Remote Extended Features (0x23) plen 13  #11 [hci0] 24.967244
        Status: Success (0x00)
        Handle: 1
        Page: 1/2
        Features: 0x01 0x00 0x00 0x00 0x00 0x00 0x00 0x00
          Secure Simple Pairing (Host Support)
< HCI Command: Remote Name Request (0x01|0x0019) plen 10   #12 [hci0] 24.967292
        Address: 00:1B:DC:F4:B0:4C (OUI 00-1B-DC)
        Page scan repetition mode: R2 (0x02)
        Page scan mode: Mandatory (0x00)
        Clock offset: 0x0000
< ACL Data TX: Handle 1 flags 0x00 dlen 10                 #13 [hci0] 24.967303
      L2CAP: Information Request (0x0a) ident 1 len 2
        Type: Extended features supported (0x0002)
> HCI Event: Command Status (0x0f) plen 4                  #14 [hci0] 24.968404
      Remote Name Request (0x01|0x0019) ncmd 1
        Status: Success (0x00)
> HCI Event: Number of Completed Packets (0x13) plen 5     #15 [hci0] 24.970119
        Num handles: 1
        Handle: 1
        Count: 1
> ACL Data RX: Handle 1 flags 0x02 dlen 16                 #16 [hci0] 24.973883
      L2CAP: Information Response (0x0b) ident 1 len 8
        Type: Extended features supported (0x0002)
        Result: Success (0x0000)
        Features: 0x00000038
          Enhanced Retransmission Mode
          Streaming Mode
          FCS Option
< ACL Data TX: Handle 1 flags 0x00 dlen 12                 #17 [hci0] 24.973922
      L2CAP: Connection Request (0x02) ident 2 len 4
        PSM: 1 (0x0001)
        Source CID: 64
< ACL Data TX: Handle 1 flags 0x00 dlen 10                 #18 [hci0] 24.973930
      L2CAP: Command Reject (0x01) ident 0 len 2
        Reason: Command not understood (0x0000)
> HCI Event: Number of Completed Packets (0x13) plen 5     #19 [hci0] 24.977118
        Num handles: 1
        Handle: 1
        Count: 1
> HCI Event: Number of Completed Packets (0x13) plen 5     #20 [hci0] 24.977595
        Num handles: 1
        Handle: 1
        Count: 1
> HCI Event: Remote Name Req Complete (0x07) plen 255      #21 [hci0] 24.978606
        Status: Success (0x00)
        Address: 00:1B:DC:F4:B0:4C (OUI 00-1B-DC)
        Name: PTS-PBAP-LAPTOP-01VKN730
@ MGMT Event: Device Connected (0x000b) plen 39       {0x0001} [hci0] 24.978628
        BR/EDR Address: 00:1B:DC:F4:B0:4C (OUI 00-1B-DC)
        Flags: 0x00000000
        Data length: 26
        Name (complete): PTS-PBAP-LAPTOP-01VKN730
> ACL Data RX: Handle 1 flags 0x02 dlen 16                 #22 [hci0] 24.980125
      L2CAP: Connection Response (0x03) ident 2 len 8
        Destination CID: 64
        Source CID: 64
        Result: Connection pending (0x0001)
        Status: No further information available (0x0000)
< ACL Data TX: Handle 1 flags 0x00 dlen 10                 #23 [hci0] 24.980175
      L2CAP: Command Reject (0x01) ident 0 len 2
        Reason: Command not understood (0x0000)
> HCI Event: Number of Completed Packets (0x13) plen 5     #24 [hci0] 24.982611
        Num handles: 1
        Handle: 1
        Count: 1
> ACL Data RX: Handle 1 flags 0x02 dlen 10                 #25 [hci0] 24.992058
      L2CAP: Information Request (0x0a) ident 8 len 2
        Type: Extended features supported (0x0002)
< ACL Data TX: Handle 1 flags 0x00 dlen 16                 #26 [hci0] 24.992087
      L2CAP: Information Response (0x0b) ident 8 len 8
        Type: Extended features supported (0x0002)
        Result: Success (0x0000)
        Features: 0x000002b8
          Enhanced Retransmission Mode
          Streaming Mode
          FCS Option
          Fixed Channels
          Unicast Connectionless Data Reception
< ACL Data TX: Handle 1 flags 0x00 dlen 10                 #27 [hci0] 24.992096
      L2CAP: Command Reject (0x01) ident 0 len 2
        Reason: Command not understood (0x0000)
> HCI Event: Number of Completed Packets (0x13) plen 5     #28 [hci0] 24.995126
        Num handles: 1
        Handle: 1
        Count: 1
> HCI Event: Number of Completed Packets (0x13) plen 5     #29 [hci0] 24.997107
        Num handles: 1
        Handle: 1
        Count: 1
> ACL Data RX: Handle 1 flags 0x02 dlen 16                 #30 [hci0] 24.998888
      L2CAP: Connection Response (0x03) ident 2 len 8
        Destination CID: 64
        Source CID: 64
        Result: Connection successful (0x0000)
        Status: No further information available (0x0000)
< ACL Data TX: Handle 1 flags 0x00 dlen 23                 #31 [hci0] 24.998921
      L2CAP: Configure Request (0x04) ident 3 len 15
        Destination CID: 64
        Flags: 0x0000
        Option: Retransmission and Flow Control (0x04) [mandatory]
          Mode: Basic (0x00)
          TX window size: 0
          Max transmit: 0
          Retransmission timeout: 0
          Monitor timeout: 0
          Maximum PDU size: 0
< ACL Data TX: Handle 1 flags 0x00 dlen 10                 #32 [hci0] 24.998929
      L2CAP: Command Reject (0x01) ident 0 len 2
        Reason: Command not understood (0x0000)
> ACL Data RX: Handle 1 flags 0x02 dlen 16                 #33 [hci0] 25.000113
      L2CAP: Configure Request (0x04) ident 9 len 8
        Destination CID: 64
        Flags: 0x0000
        Option: Maximum Transmission Unit (0x01) [mandatory]
          MTU: 1024
< ACL Data TX: Handle 1 flags 0x00 dlen 18                 #34 [hci0] 25.000146
      L2CAP: Configure Response (0x05) ident 9 len 10
        Source CID: 64
        Flags: 0x0000
        Result: Success (0x0000)
        Option: Maximum Transmission Unit (0x01) [mandatory]
          MTU: 1024
< ACL Data TX: Handle 1 flags 0x00 dlen 10                 #35 [hci0] 25.000154
      L2CAP: Command Reject (0x01) ident 0 len 2
        Reason: Command not understood (0x0000)
> HCI Event: Number of Completed Packets (0x13) plen 5     #36 [hci0] 25.002069
        Num handles: 1
        Handle: 1
        Count: 1
> HCI Event: Number of Completed Packets (0x13) plen 5     #37 [hci0] 25.002614
        Num handles: 1
        Handle: 1
        Count: 1
> HCI Event: Number of Completed Packets (0x13) plen 5     #38 [hci0] 25.003884
        Num handles: 1
        Handle: 1
        Count: 1
> ACL Data RX: Handle 1 flags 0x02 dlen 18                 #39 [hci0] 25.004988
      L2CAP: Configure Response (0x05) ident 3 len 10
        Source CID: 64
        Flags: 0x0000
        Result: Success (0x0000)
        Option: Maximum Transmission Unit (0x01) [mandatory]
          MTU: 672
< ACL Data TX: Handle 1 flags 0x00 dlen 10                 #40 [hci0] 25.005026
      L2CAP: Command Reject (0x01) ident 0 len 2
        Reason: Command not understood (0x0000)
< ACL Data TX: Handle 1 flags 0x00 dlen 24                 #41 [hci0] 25.005102
      Channel: 64 len 20 [PSM 1 mode Basic (0x00)] {chan 0}
      SDP: Service Search Attribute Request (0x06) tid 0 len 15
        Search pattern: [len 5]
          Sequence (6) with 3 bytes [8 extra bits] len 5
            UUID (3) with 2 bytes [0 extra bits] len 3
              Phonebook Access Server (0x112f)
        Max record count: 65535
        Attribute list: [len 7]
          Sequence (6) with 5 bytes [8 extra bits] len 7
            Unsigned Integer (1) with 4 bytes [0 extra bits] len 5
              0x0000ffff
        Continuation state: 0
> HCI Event: Number of Completed Packets (0x13) plen 5     #42 [hci0] 25.005402
        Num handles: 1
        Handle: 1
        Count: 1
> HCI Event: Number of Completed Packets (0x13) plen 5     #43 [hci0] 25.007608
        Num handles: 1
        Handle: 1
        Count: 1
> HCI Event: Number of Completed Packets (0x13) plen 5     #44 [hci0] 25.008867
        Num handles: 1
        Handle: 1
        Count: 1
> ACL Data RX: Handle 1 flags 0x02 dlen 115                #45 [hci0] 25.012640
      Channel: 64 len 111 [PSM 1 mode Basic (0x00)] {chan 0}
      SDP: Service Search Attribute Response (0x07) tid 0 len 106
        Attribute bytes: 103
          Attribute list: [len 99] {position 0}
            Attribute: Service Record Handle (0x0000) [len 2]
              0x00010003
            Attribute: Service Class ID List (0x0001) [len 2]
              UUID (3) with 2 bytes [0 extra bits] len 3
                Phonebook Access Server (0x112f)
            Attribute: Protocol Descriptor List (0x0004) [len 2]
              Sequence (6) with 3 bytes [8 extra bits] len 5
                UUID (3) with 2 bytes [0 extra bits] len 3
                  L2CAP (0x0100)
              Sequence (6) with 5 bytes [8 extra bits] len 7
                UUID (3) with 2 bytes [0 extra bits] len 3
                  RFCOMM (0x0003)
                Unsigned Integer (1) with 1 byte [0 extra bits] len 2
                  0x02
              Sequence (6) with 3 bytes [8 extra bits] len 5
                UUID (3) with 2 bytes [0 extra bits] len 3
                  OBEX (0x0008)
            Attribute: Bluetooth Profile Descriptor List (0x0009) [len 2]
              Sequence (6) with 6 bytes [8 extra bits] len 8
                UUID (3) with 2 bytes [0 extra bits] len 3
                  Phonebook Access (0x1130)
                Unsigned Integer (1) with 2 bytes [0 extra bits] len 3
                  0x0102
            Attribute: Unknown (0x0100) [len 2]
              Phonebook Access PSE PTS [len 24]
            Attribute: Unknown (0x0200) [len 2]
              0x1005
            Attribute: Unknown (0x0314) [len 2]
              0x0f
            Attribute: Unknown (0x0317) [len 2]
              0x000003ff
        Continuation state: 0
< HCI Command: Authentication Requ.. (0x01|0x0011) plen 2  #46 [hci0] 25.012851
        Handle: 1
< ACL Data TX: Handle 1 flags 0x00 dlen 12                 #47 [hci0] 25.012868
      L2CAP: Disconnection Request (0x06) ident 4 len 4
        Destination CID: 64
        Source CID: 64
> HCI Event: Command Status (0x0f) plen 4                  #48 [hci0] 25.013596
      Authentication Requested (0x01|0x0011) ncmd 1
        Status: Success (0x00)
> HCI Event: Link Key Request (0x17) plen 6                #49 [hci0] 25.013865
        Address: 00:1B:DC:F4:B0:4C (OUI 00-1B-DC)
< HCI Command: Link Key Request R.. (0x01|0x000b) plen 22  #50 [hci0] 25.013895
        Address: 00:1B:DC:F4:B0:4C (OUI 00-1B-DC)
        Link key: 9814f2aa4efa0066429589138028d2ce
> HCI Event: Number of Completed Packets (0x13) plen 5     #51 [hci0] 25.015090
        Num handles: 1
        Handle: 1
        Count: 1
> HCI Event: Command Complete (0x0e) plen 10               #52 [hci0] 25.017504
      Link Key Request Reply (0x01|0x000b) ncmd 1
        Status: Success (0x00)
        Address: 00:1B:DC:F4:B0:4C (OUI 00-1B-DC)
> ACL Data RX: Handle 1 flags 0x02 dlen 12                 #53 [hci0] 25.022539
      L2CAP: Disconnection Response (0x07) ident 4 len 4
        Destination CID: 64
        Source CID: 64
< ACL Data TX: Handle 1 flags 0x00 dlen 10                 #54 [hci0] 25.022575
      L2CAP: Command Reject (0x01) ident 0 len 2
        Reason: Command not understood (0x0000)
> HCI Event: Number of Completed Packets (0x13) plen 5     #55 [hci0] 25.025118
        Num handles: 1
        Handle: 1
        Count: 1
> HCI Event: Auth Complete (0x06) plen 3                   #56 [hci0] 25.025364
        Status: Success (0x00)
        Handle: 1
< HCI Command: Set Connection Encr.. (0x01|0x0013) plen 3  #57 [hci0] 25.025392
        Handle: 1
        Encryption: Enabled (0x01)
> HCI Event: Command Status (0x0f) plen 4                  #58 [hci0] 25.026130
      Set Connection Encryption (0x01|0x0013) ncmd 1
        Status: Success (0x00)
> HCI Event: Encryption Change (0x08) plen 4               #59 [hci0] 25.040205
        Status: Success (0x00)
        Handle: 1
        Encryption: Enabled with E0 (0x01)
< HCI Command: Read Encryption Key.. (0x05|0x0008) plen 2  #60 [hci0] 25.040234
        Handle: 1
> HCI Event: Command Complete (0x0e) plen 7                #61 [hci0] 25.040590
      Read Encryption Key Size (0x05|0x0008) ncmd 1
        Status: Success (0x00)
        Handle: 1
        Key size: 16
< ACL Data TX: Handle 1 flags 0x00 dlen 12                 #62 [hci0] 25.040621
      L2CAP: Connection Request (0x02) ident 5 len 4
        PSM: 4101 (0x1005)
        Source CID: 65
> HCI Event: Number of Completed Packets (0x13) plen 5     #63 [hci0] 25.042609
        Num handles: 1
        Handle: 1
        Count: 1
> ACL Data RX: Handle 1 flags 0x02 dlen 16                 #64 [hci0] 25.045119
      L2CAP: Connection Response (0x03) ident 5 len 8
        Destination CID: 64
        Source CID: 65
        Result: Connection pending (0x0001)
        Status: No further information available (0x0000)
< ACL Data TX: Handle 1 flags 0x00 dlen 10                 #65 [hci0] 25.045147
      L2CAP: Command Reject (0x01) ident 0 len 2
        Reason: Command not understood (0x0000)
> HCI Event: Number of Completed Packets (0x13) plen 5     #66 [hci0] 25.047592
        Num handles: 1
        Handle: 1
        Count: 1
> HCI Event: Link Key Request (0x17) plen 6                #67 [hci0] 25.050265
        Address: 00:1B:DC:F4:B0:4C (OUI 00-1B-DC)
< HCI Command: Link Key Request R.. (0x01|0x000b) plen 22  #68 [hci0] 25.050307
        Address: 00:1B:DC:F4:B0:4C (OUI 00-1B-DC)
        Link key: 9814f2aa4efa0066429589138028d2ce
> HCI Event: Command Complete (0x0e) plen 10               #69 [hci0] 25.052881
      Link Key Request Reply (0x01|0x000b) ncmd 1
        Status: Success (0x00)
        Address: 00:1B:DC:F4:B0:4C (OUI 00-1B-DC)
> ACL Data RX: Handle 1 flags 0x02 dlen 16                 #70 [hci0] 25.067161
      L2CAP: Connection Response (0x03) ident 5 len 8
        Destination CID: 64
        Source CID: 65
        Result: Connection successful (0x0000)
        Status: No further information available (0x0000)
< ACL Data TX: Handle 1 flags 0x00 dlen 27                 #71 [hci0] 25.067194
      L2CAP: Configure Request (0x04) ident 6 len 19
        Destination CID: 64
        Flags: 0x0000
        Option: Maximum Transmission Unit (0x01) [mandatory]
          MTU: 32767
        Option: Retransmission and Flow Control (0x04) [mandatory]
          Mode: Enhanced Retransmission (0x03)
          TX window size: 63
          Max transmit: 3
          Retransmission timeout: 2000
          Monitor timeout: 12000
          Maximum PDU size: 1004
< ACL Data TX: Handle 1 flags 0x00 dlen 10                 #72 [hci0] 25.067202
      L2CAP: Command Reject (0x01) ident 0 len 2
        Reason: Command not understood (0x0000)
> ACL Data RX: Handle 1 flags 0x02 dlen 30                 #73 [hci0] 25.067809
      L2CAP: Configure Request (0x04) ident 10 len 22
        Destination CID: 65
        Flags: 0x0000
        Option: Maximum Transmission Unit (0x01) [mandatory]
          MTU: 4096
        Option: Retransmission and Flow Control (0x04) [mandatory]
          Mode: Enhanced Retransmission (0x03)
          TX window size: 8
          Max transmit: 16
          Retransmission timeout: 0
          Monitor timeout: 0
          Maximum PDU size: 1691
        Option: Frame Check Sequence (0x05) [mandatory]
          FCS: No FCS (0x00)
< ACL Data TX: Handle 1 flags 0x00 dlen 29                 #74 [hci0] 25.067844
      L2CAP: Configure Response (0x05) ident 10 len 21
        Source CID: 64
        Flags: 0x0000
        Result: Success (0x0000)
        Option: Maximum Transmission Unit (0x01) [mandatory]
          MTU: 4096
        Option: Retransmission and Flow Control (0x04) [mandatory]
          Mode: Enhanced Retransmission (0x03)
          TX window size: 8
          Max transmit: 16
          Retransmission timeout: 2000
          Monitor timeout: 12000
          Maximum PDU size: 1004
< ACL Data TX: Handle 1 flags 0x00 dlen 10                 #75 [hci0] 25.067853
      L2CAP: Command Reject (0x01) ident 0 len 2
        Reason: Command not understood (0x0000)
> HCI Event: Number of Completed Packets (0x13) plen 5     #76 [hci0] 25.070116
        Num handles: 1
        Handle: 1
        Count: 1
> HCI Event: Number of Completed Packets (0x13) plen 5     #77 [hci0] 25.072107
        Num handles: 1
        Handle: 1
        Count: 1
> ACL Data RX: Handle 1 flags 0x02 dlen 29                 #78 [hci0] 25.072679
      L2CAP: Configure Response (0x05) ident 6 len 21
        Source CID: 65
        Flags: 0x0000
        Result: Success (0x0000)
        Option: Maximum Transmission Unit (0x01) [mandatory]
          MTU: 4096
        Option: Retransmission and Flow Control (0x04) [mandatory]
          Mode: Enhanced Retransmission (0x03)
          TX window size: 24
          Max transmit: 0
          Retransmission timeout: 256
          Monitor timeout: 256
          Maximum PDU size: 1004
< ACL Data TX: Handle 1 flags 0x00 dlen 10                 #79 [hci0] 25.072714
      L2CAP: Command Reject (0x01) ident 0 len 2
        Reason: Command not understood (0x0000)
> HCI Event: Number of Completed Packets (0x13) plen 5     #80 [hci0] 25.072726
        Num handles: 1
        Handle: 1
        Count: 1
< ACL Data TX: Handle 1 flags 0x00 dlen 43                 #81 [hci0] 25.072900
      Channel: 64 len 39 ctrl 0x0000 [PSM 4101 mode Enhanced Retransmission (0x03)] {chan 0}
      I-frame: Unsegmented TxSeq 0 ReqSeq 0
        00 00 80 00 23 10 00 10 00 46 00 13 79 61 35 f0  ....#....F..ya5.
        f0 c5 11 d8 09 66 08 00 20 0c 9a 66 4c 00 09 10  .....f.. ..fL...
        04 00 00 03 ff c9 1d                             .......         
> HCI Event: Number of Completed Packets (0x13) plen 5     #82 [hci0] 25.073868
        Num handles: 1
        Handle: 1
        Count: 1
> HCI Event: Number of Completed Packets (0x13) plen 5     #83 [hci0] 25.075088
        Num handles: 1
        Handle: 1
        Count: 1
> HCI Event: Number of Completed Packets (0x13) plen 5     #84 [hci0] 25.077070
        Num handles: 1
        Handle: 1
        Count: 1
> ACL Data RX: Handle 1 flags 0x02 dlen 8                  #85 [hci0] 25.078746
      Channel: 65 len 4 ctrl 0x0101 [PSM 4101 mode Enhanced Retransmission (0x03)] {chan 0}
      S-frame: Receiver Ready (RR) ReqSeq 1
        01 01 d5 e8                                      ....            
> ACL Data RX: Handle 1 flags 0x02 dlen 42                 #86 [hci0] 25.349643
      Channel: 65 len 38 ctrl 0x0100 [PSM 4101 mode Enhanced Retransmission (0x03)] {chan 0}
      I-frame: Unsegmented TxSeq 0 ReqSeq 1
        00 01 c1 00 22 12 00 10 00 4d 00 1b 00 10 13 c2  ...."....M......
        15 94 b5 5a 18 33 9b a8 11 b7 11 25 df 3e 01 01  ...Z.3.....%.>..
        00 02 01 00 5a 0b                                ....Z.          
< ACL Data TX: Handle 1 flags 0x00 dlen 64                 #87 [hci0] 25.349824
      Channel: 64 len 60 ctrl 0x0102 [PSM 4101 mode Enhanced Retransmission (0x03)] {chan 0}
      I-frame: Unsegmented TxSeq 1 ReqSeq 1
        02 01 80 00 38 10 00 10 00 46 00 13 79 61 35 f0  ....8....F..ya5.
        f0 c5 11 d8 09 66 08 00 20 0c 9a 66 4c 00 09 10  .....f.. ..fL...
        04 00 00 03 ff 4e 00 15 00 10 e3 1e ed 53 4a 04  .....N.......SJ.
        15 91 14 75 4d e8 8b b4 02 1b ca 52              ...uM......R    
> HCI Event: Number of Completed Packets (0x13) plen 5     #88 [hci0] 25.352555
        Num handles: 1
        Handle: 1
        Count: 1
> ACL Data RX: Handle 1 flags 0x02 dlen 8                  #89 [hci0] 25.354950
      Channel: 65 len 4 ctrl 0x0201 [PSM 4101 mode Enhanced Retransmission (0x03)] {chan 0}
      S-frame: Receiver Ready (RR) ReqSeq 2
        01 02 95 e9                                      ....            
> ACL Data RX: Handle 1 flags 0x02 dlen 12                 #90 [hci0] 29.638181
      L2CAP: Disconnection Request (0x06) ident 11 len 4
        Destination CID: 65
        Source CID: 64
< ACL Data TX: Handle 1 flags 0x00 dlen 12                 #91 [hci0] 29.638242
      L2CAP: Disconnection Response (0x07) ident 11 len 4
        Destination CID: 65
        Source CID: 64
< ACL Data TX: Handle 1 flags 0x00 dlen 10                 #92 [hci0] 29.638252
      L2CAP: Command Reject (0x01) ident 0 len 2
        Reason: Command not understood (0x0000)
> HCI Event: Number of Completed Packets (0x13) plen 5     #93 [hci0] 29.646912
        Num handles: 1
        Handle: 1
        Count: 1
> HCI Event: Number of Completed Packets (0x13) plen 5     #94 [hci0] 29.649829
        Num handles: 1
        Handle: 1
        Count: 1
> HCI Event: Disconnect Complete (0x05) plen 4             #95 [hci0] 29.650263
        Status: Success (0x00)
        Handle: 1
        Reason: Remote Device Terminated due to Power Off (0x15)
@ MGMT Event: Device Disconnected (0x000c) plen 8     {0x0001} [hci0] 29.650290
        BR/EDR Address: 00:1B:DC:F4:B0:4C (OUI 00-1B-DC)
        Reason: Connection terminated by remote host (0x03)

**Comment by Vudentz** [comment]
```
< ACL Data TX: Handle 1 flags 0x00 dlen 64 https://github.com/bluez/bluez/pull/87 [hci0] 25.349824
Channel: 64 len 60 ctrl 0x0102 [PSM 4101 mode Enhanced Retransmission (0x03)] {chan 0}
I-frame: Unsegmented TxSeq 1 ReqSeq 1
02 01 80 00 38 10 00 10 00 46 00 13 79 61 35 f0 ....8....F..ya5.
f0 c5 11 d8 09 66 08 00 20 0c 9a 66 4c 00 09 10 .....f.. ..fL...
04 00 00 03 ff 4e 00 15 00 10 e3 1e ed 53 4a 04 .....N.......SJ.
15 91 14 75 4d e8 8b b4 02 1b ca 52 ...uM......R
```

Kind hard to understand what is this response without decoding, it looks like this is not at the GAP authentication but some custom PBAP authentication.

**Comment by Vudentz** [comment]
@sanchipsync what md5 key did you use, this is hardcoded in gobex:

https://github.com/bluez/bluez/blob/master/gobex/gobex.c#L586

**Comment by sanchipsync** [comment]
@Vudentz I tried  by sharing passkey between bluetoothd and obexd by a simple workaround(Patch attached - _passkey_sharing_bluetoothd_obexd.patch_). Still seeing the same authentication issue.

Attaching the bluetoothd log, obexd log and btmon dump with above workaround patch.
[passkey_sharing_bluetoothd_obexd.patch.txt](https://github.com/bluez/bluez/files/14039316/passkey_sharing_bluetoothd_obexd.patch.txt)

[btmon_pbap_failing_log.txt](https://github.com/bluez/bluez/files/14039293/btmon_pbap_failing_log.txt)
[obex_failing_log.txt](https://github.com/bluez/bluez/files/14039294/obex_failing_log.txt)
[bluez_failing_log.txt](https://github.com/bluez/bluez/files/14039295/bluez_failing_log.txt)

**Comment by Vudentz** [comment]
> @Vudentz I tried by sharing passkey between bluetoothd and obexd by a simple workaround(Patch attached - _passkey_sharing_bluetoothd_obexd.patch_). Still seeing the same authentication issue.
> 
> Attaching the bluetoothd log, obexd log and btmon dump with above workaround patch. [passkey_sharing_bluetoothd_obexd.patch.txt](https://github.com/bluez/bluez/files/14039316/passkey_sharing_bluetoothd_obexd.patch.txt)
> 
> [btmon_pbap_failing_log.txt](https://github.com/bluez/bluez/files/14039293/btmon_pbap_failing_log.txt) [obex_failing_log.txt](https://github.com/bluez/bluez/files/14039294/obex_failing_log.txt) [bluez_failing_log.txt](https://github.com/bluez/bluez/files/14039295/bluez_failing_log.txt)

I don't recall how we did pass in the past, but I think there was something you need to enter at the PTS side to set what key/data shall be used in the authentication, not sure if this has been changed that it now requires the link-key to be used instead.

**Comment by sanchipsync** [comment]
@Vudentz Thanks for your inputs. Got the test to pass by setting the auth password in PTS tool.
