### ISSUE TITLE
Downgrade to Bluez-5.70.2 solved my problem

### ISSUE THREAD

**Issue by berbigou** [bluez/bluez#733]
Hello,
on Archlinux / Plasma / 6.7.0-arch3-1
my Logitech mouse M650 L kept disconnecting (BT icon flickering, not usable) on Bluez-5.72.2, like wrong keys after a new association.
downgrade on Bluez-5.71.3 didn't help (but I didn't test long)

downgrade on Bluez-5.70.2 solved my problem...

So, I post this and hope it will help.

Thanks for your work
Greetings from France

Berbigou

**Comment by Vudentz** [comment]
@berbigou any chance to gather some logs, btmon, bluetoothd, etc?

**Comment by berbigou** [comment]
(I know I should)
Sorry, as I found a fix, I had no time to dig in...

I will try to investigate. what logs would help (and where are they, please ) ?
Thanks for answering

**Comment by berbigou** [comment]
Sorry. 
I came back to bluez-latest (5.72.2) and everything is OK...
Must be stupid.
Excuse me.

**Comment by Vudentz** [comment]
Maybe something with the key type is quite right when switching versions or something, or the storage is corrupted and you need to repair to have it fixed, anyway if it is fixed please close it.
