### ISSUE TITLE
Enabling characteristic notifications on a RaspberryPi BLE server does not work consistently

### ISSUE THREAD

**Issue by MoldovanRaduOctavian22** [bluez/bluez#757]
I am developing an Android app that needs to exchange data through Bluetooth LE with a RaspberryPi running a Bluez BLE server . I use my Android app to write the CCC descriptor to 0100 in order to enable notifications, but when I run my BLE server on the RaspberryPi it sometimes seems to misinterpret the writing of that descriptor and not enable the characteristic notifications. I found this out by monitoring the DBUS Bluez messages:

When notifications get enabled and things work fine, the StartNotify method gets called when I write the CCC descriptor:
`
Type=method_call  Endian=l  Flags=1  Version=1 Cookie=2651 Sender=:1.16  Destination=:1.99  Path=/org/bluez/dbz_application/service_0/char_1  Interface=org.bluez.GattCharacteristic1  Member=StartNotify UniqueName=:1.16 MESSAGE "" { };
`

When the notifications don't trigger, the WriteValue for the descriptor method gets called:

`
Type=method_call  Endian=l  Flags=0  Version=1 Cookie=2844 Sender=:1.16  Destination=:1.107  Path=/org/bluez/dbz_application/service_0/char_1/desc_0  Interface=org.bluez.GattDescriptor1  Member=WriteValue UniqueName=:1.16 MESSAGE "aya{sv}" { ARRAY "y" { BYTE 1; BYTE 0; }; ARRAY "{sv}" { DICT_ENTRY "sv" { STRING "device"; VARIANT "o" { OBJECT_PATH "/org/bluez/hci0/dev_74_B0_0A_B8_27_BF"; }; }; DICT_ENTRY "sv" { STRING "link"; VARIANT "s" { STRING "LE"; }; }; DICT_ENTRY "sv" { STRING "mtu"; VARIANT "q" { UINT16 517; }; }; }; };
`

The problem is encountered randomly, when I run my program notifications either work fine or not at all and I didn't find any particular reason for this.

I have also noticed that running the BLE server functionality by itself never made me run into this issue. I use the Bluez DBUS API to create a BLE server into a program that does many other things, and works on several threads. This is the case in which the issue appears infrequently.

Are you aware of any reason for the problem ?

I'll try my best to find a solution and reach you out if I discover something.

**Comment by beku-epitome** [comment]
I get the impression that you are creating your own GattDescriptor1 instead of adding the "notify" flag to the GattCharacteristic1's Flags property. The CCC descriptor is created by BlueZ internally for each characteristic that has "notify" or "indicate" flag set, your own descriptor is conflicting with it.

**Comment by MoldovanRaduOctavian22** [comment]
> I get the impression that you are creating your own GattDescriptor1 instead of adding the "notify" flag to the GattCharacteristic1's Flags property. The CCC descriptor is created by BlueZ internally for each characteristic that has "notify" or "indicate" flag set, your own descriptor is conflicting with it.

I was adding the notify flag to the characteristic, but I thought that I also have to create the CCC descriptor manually. Removing the code that creates the descriptor solved my problem. Thank you for helping me out!
