### ISSUE TITLE
some suggestion 

### ISSUE THREAD

**Issue by luoyuyi111** [bluez/bluez#789]
Hello, I am a Bluetooth developer, and to be honest, using bluez on linux at present has a relatively high threshold for a novice. Because there are many Bluetooth protocols, reading the code will be easy to get confused.

I have a suggestion as to whether developers should add code comments to their code as much as possible, especially for each member of the structure, explaining what they do. This makes it easier to read the code. For example: I am checking the absolute volume of a problem and see a "source_watch" variable, I don't know what it means, does it refer to the other device source or my own source?

Thanks for listening

**Comment by mikael-marvin** [comment]
Hello luoyuyi111!
Can i contact you for some suggestions in pairing a device and using custom agents?
sorry for commenting here.
