### ISSUE TITLE
a question about fd

### ISSUE THREAD

**Issue by luoyuyi111** [bluez/bluez#795]
```
struct media_transport *media_transport_create(struct btd_device *device,
						const char *remote_endpoint,
						uint8_t *configuration,
						size_t size, void *data,
						void *stream)
{
	struct media_endpoint *endpoint = data;
	struct media_transport *transport;
	const struct media_transport_ops *ops;
	static int fd = 0;

	transport = g_new0(struct media_transport, 1);
	if (device)
		transport->device = device;
	else
		transport->adapter = media_endpoint_get_btd_adapter(endpoint);

	transport->endpoint = endpoint;
	transport->configuration = util_memdup(configuration, size);
	transport->size = size;
	transport->remote_endpoint = remote_endpoint;

	if (device)
		transport->path = g_strdup_printf("%s/fd%d",
					remote_endpoint ? remote_endpoint :
					device_get_path(device), fd++);
```

In the above code, why does the fd variable keep growing and what are the considerations?

Because path contains the mac address, it can already distinguish between multiple device connections. At present, I encounter the same device, repeatedly connected and disconnected, this fd has been growing, will there be any risk

**Comment by Vudentz** [comment]
@luoyuyi111 you can have multiple transports to the same device, so the fd portion is used to create a unique object path. If you are suggesting it could loop around and then possible clash, that is very unlikely given that needs to happens within the same connection as the transport objects are destroyed on disconnection.
