### ISSUE TITLE
GATT server: AcquireNotify messages are shared between clients

### ISSUE THREAD

**Issue by beku-epitome** [bluez/bluez#820]
This is a follow-up on #460. In 8eb1dee the AcquireWrite and AcquireNotify were made directional towards a single client device. I was reviewing the code and I found that the notifications received from the pipe are not sent to the pipe owning client, but to all subscribed clients:
https://github.com/bluez/bluez/blob/89cb88b0f030cd1b4dc96cfd1760332122957ec3/src/gatt-database.c#L2589-L2608

Please fix this bug so only the pipe's client gets the notification.

**Comment by Vudentz** [comment]
@beku-epitome Please check with the changes above, and please don't take this long to give feedback otherwise we may get into the same situation where we think it was fixed but user hasn't actually validate the fix properly.
