### ISSUE TITLE
Bluetooth not working

### ISSUE THREAD

**Issue by natesworks** [bluez/bluez#849]
src/plugin.c:init_plugin() System does not support ccp plugin

no adapters in bluetoothctl

**Comment by natesworks** [comment]
also not blocked by rfkill

**Comment by StuffOfSonny** [comment]
I am also having this issue.

**Comment by natesworks** [comment]
I use arch btw

**Comment by abhigyanmadhukalya** [comment]
Having the same problem on Aurora/Bluefin (Ublue OS).

**Comment by Vudentz** [comment]
Version? Controller, HCI traces, etc, might be required as well to investigate what is going on.

**Comment by StuffOfSonny** [comment]
Arch Linux 6.9.1-zen1-1-zen, I only have a brief moment of availability so that's all I could grab at the moment.

**Comment by natesworks** [comment]
Im using the normal kernel trying to enable hci0 shows file not found for some reason

**Comment by Harroy11** [comment]
Arch, Linux 6.9.1 normal, bluez5.76, MediaTek PCIe adapter.
Bluetoothctl shows nothing.

**Comment by natesworks** [comment]
I also have mediatek maybe related(?)

**Comment by abhigyanmadhukalya** [comment]
I also have a MediaTek adapter for bluetooth and bluez 5.75, `bluetoothctl` shows nothing and `journalctl` shows no error.

**Comment by Vudentz** [comment]
Anything on the traces? Perhaps the firmware is not being loaded correctly or something?

**Comment by tetoNidan** [comment]
`sudo dmesg | grep -i bluetooth`

    Bluetooth: Core ver 2.22
    NET: Registered PF_BLUETOOTH protocol family
    Bluetooth: HCI device and connection manager initialized
    Bluetooth: HCI socket layer initialized
    Bluetooth: L2CAP socket layer initialized
    Bluetooth: SCO socket layer initialized
    bluetooth hci0: Direct firmware load for mediatek/BT_RAM_CODE_MT7961_1a_2_hdr.bin failed with error -2
    Bluetooth: hci0: Failed to load firmware file (-2)
    Bluetooth: hci0: Failed to set up firmware (-2)
    Bluetooth: hci0: HCI Enhanced Setup Synchronous Connection command is advertised, but not supported.
    Bluetooth: BNEP (Ethernet Emulation) ver 1.3
    Bluetooth: BNEP filters: protocol multicast
    Bluetooth: BNEP socket layer initialized

**Comment by Harroy11** [comment]
I got the exact same output

**Comment by mllull** [comment]
The bug is posted (and solved) here: https://bbs.archlinux.org/viewtopic.php?id=295942
(more info no this bugzilla post: https://bugzilla.kernel.org/show_bug.cgi?id=218757).

Seems to be a bug in Kernel firmwares related to `MediaTek` (I also have it in my computer).

You can solve it by create a *symlink* as specified in first link or apply a Kernel patch.

This bug seems to be unrelated to *bluez*, so maybe this issue can be closed and keep this post as per documentation about this kernel bug.

**Comment by natesworks** [comment]
why is no maintainer replying

**Comment by natesworks** [comment]
Solution: sudo ln -s /lib/firmware/mediatek/BT_RAM_CODE_MT7961_1_2_hdr.bin.zst /lib/firmware/mediatek/BT_RAM_CODE_MT7961_1a_2_hdr.bin.zst

If this didn't work feel free to reopen the issue. Thanks @Vudentz for helping!

**Comment by natesworks** [comment]
This will be fixed in kernel 6.9.2

**Comment by StuffOfSonny** [comment]
Was not fixed in kernel 6.9.2
![image](https://github.com/bluez/bluez/assets/61560546/384bb663-6094-43fc-a621-2e99508cf51e)

**Comment by natesworks** [comment]
> Was not fixed in kernel 6.9.2
> ![image](https://github.com/bluez/bluez/assets/61560546/384bb663-6094-43fc-a621-2e99508cf51e)
> 

Well just use the comment I marked as the solution. Also your using the zen kernel.

**Comment by StuffOfSonny** [comment]
> > Was not fixed in kernel 6.9.2
> > ![image](https://private-user-images.githubusercontent.com/61560546/335389758-384bb663-6094-43fc-a621-2e99508cf51e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxOTA0ODAsIm5iZiI6MTcxNzE5MDE4MCwicGF0aCI6Ii82MTU2MDU0Ni8zMzUzODk3NTgtMzg0YmI2NjMtNjA5NC00M2ZjLWE2MjEtMmU5OTUwOGNmNTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDIxMTYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkZDUxODgxZGVlZTMyZTVjYTk5YzkzZDM4NDIwODNmYjZiYTllOTUzZGNhZTFiYzBiNWM4NDY2M2Q3ZjBjODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4m70whtuUJDaN054LkANv2Ed2ZeVjCs42Shu5AweMZ0)
> 
> Well just use the comment I marked as the solution. Also your using the zen kernel.

Yes, as mentioned above

> Arch Linux 6.9.1-zen1-1-zen, I only have a brief moment of availability so that's all I could grab at the moment.

Anywho, I did try the symlink solution and while it did make the adapter show up in system settings, it would fail to scan for any devices.
