### ISSUE TITLE
Disable Hands Free permanently

### ISSUE THREAD

**Issue by CoutHi** [bluez/bluez#864]
I have searched the internet to find a solution for a while, but I couldn't find one. So if there really is none, implementing a way to permanently disable HFP sinks would be very nice. It is incredibly annoying and is the last annoyance I have left with Linux.

**Comment by Vudentz** [comment]
> I have searched the internet to find a solution for a while, but I couldn't find one. So if there really is none, implementing a way to permanently disable HFP sinks would be very nice. It is incredibly annoying and is the last annoyance I have left with Linux.

HFP is not implemented as a built-in plugin in BlueZ for some time, otherwise you could just disable the plugin, this usually comes from the likes of pipewire, pulseaudio or if you have something like oFono in your system.
