### ISSUE TITLE
LE Audio : The kernel does not have the LE Remove ISO Data Path command and related functions.

### ISSUE THREAD

**Issue by dabeixiaomibujiatang** [bluez/bluez#883]
kernel6.6 + bluez5.75  LE Audio
I've encountered some issues. After playing a song and then waiting for a while before trying to play again, my controller fails to create the CIS again. I noticed that during this interval, it disconnects the CIS connect and removes the CIG, but it does not execute the Remove ISO Data Path before removing the CIG. Although I know that in the Core 5.4 Section 7.8.100 LE Remove CIG command, it states, "This command shall also remove the isochronous data paths that are associated with the Connection_Handles of the CIS configurations, which is equivalent to issuing the HCI_LE_Remove_ISO_Data_Path command (see Section 7.8.110)." I wanted to add the Remove ISO Data Path before removing the CIG, but the kernel does not have the LE Remove ISO Data Path command and related functions.

**Comment by Vudentz** [comment]
Most likely a controller bug since HCI_LE_Remove_CIG is equivalent to issuing HCI_LE_Remove_ISO_Data_Path:

```
BLUETOOTH CORE SPECIFICATION Version 5.4 | Vol 4, Part E
page 2571:

7.8.100 LE Remove CIG command

This command shall also remove the isochronous data paths that are
associated with the Connection_Handles of the CIS configurations, which is
equivalent to issuing the HCI_LE_Remove_ISO_Data_Path command (see
Section 7.8.110).
```
