### ISSUE TITLE
Support host and client connections simultaneously

### ISSUE THREAD

**Issue by Raraph84** [bluez/bluez#934]
Hi !
I want to use my Raspberry Pi as a bluetooth keyboard/mouse relay, but it does not works
I found this fork that is working but is very old https://github.com/Dreamsorcerer/bluez
Is the official bluez was updated to support host and client connections simultaneously and my implementation is bad or it does not support it yet?

**Comment by Vudentz** [comment]
@Raraph84 perhaps related to https://github.com/bluez/bluez/issues/584

**Comment by Raraph84** [comment]
Yes my bad it was just fixed 2 weeks ago
