### ISSUE TITLE
After CIS disconnects, Bluez will turn on scan automatically.

### ISSUE THREAD

**Issue by carlchenzekun** [bluez/bluez#959]
The current logic is whenever Bluez receives a Disconnect Complete Event, it will turn the scan enable on to re-connect.
It does not check the connection handle got disconnected is a ACL handle or ISO handle. In the case below, the ACL connection is still alive but user turns off streaming. Bluez will enter scan mode which will interfere when users starts streaming again in the future.
![image](https://github.com/user-attachments/assets/749021df-08e6-44b0-a4f7-b16aa63406e5)
[jabra1_BluezTurnsOnScan.zip](https://github.com/user-attachments/files/17063819/jabra1_BluezTurnsOnScan.zip)

**Comment by Vudentz** [comment]
https://patchwork.kernel.org/project/bluetooth/patch/20240919165253.847475-1-luiz.dentz@gmail.com/

**Comment by carlchenzekun** [comment]
Thanks a lot Luiz

**Comment by Vudentz** [comment]
> Thanks a lot Luiz

Have you confirm the above changes fixed the problem?

**Comment by carlchenzekun** [comment]
> > Thanks a lot Luiz
> 
> Have you confirm the above changes fixed the problem?

I need to have qa to verify that since I don't have enough bandwidth. But looking at the change it is what I meant... checking the connection type at hci_disconnect. I will keep it open and let you know once have some results. It will need a kernel rebuilt.

**Comment by Vudentz** [comment]
> > > Thanks a lot Luiz
> > 
> > 
> > Have you confirm the above changes fixed the problem?
> 
> I need to have qa to verify that since I don't have enough bandwidth. But looking at the change it is what I meant... checking the connection type at hci_disconnect. I will keep it open and let you know once have some results. It will need a kernel rebuilt.

Yeah, the change is pretty straight forward, what I more concern about is if there are some other use case that maybe need to be addressed thus having some testing is probably a good idea.

**Comment by Vudentz** [comment]
@carlchenzekun any update regarding this?

**Comment by carlchenzekun** [comment]
> @carlchenzekun any update regarding this?

Hi Luiz, gathering the log and will discuss on Thursday's sync up as well as summerize here.

**Comment by carlchenzekun** [comment]
Hi Luiz,

Applying the patch, I don't see the scan turned on after CIS got disconnected anymore. Normal LE reconnection procedure is not affected.

One thing I noticed is CIG get removed and immediately reconfigured (in screenshot) after CIS disconnection. It does not affect normal operation so I will close this issue for now. 
![image](https://github.com/user-attachments/assets/3b1125f6-1a38-469b-b473-9fe1a54081f7)
