### ISSUE TITLE
[Question] Running 2 GATT server at the same time on different BLE USB dongles (HCI) but on one Raspberry pi (Bluez 5.50)

### ISSUE THREAD

**Issue by inonoob** [bluez/bluez#97]
Hello everyone, 

question: is it possible to have 2 GATT Server at the same time on 2 separate Bluetooth USB dongle on one Raspberry Pi. 
I use the GATT example from Bluez to have just one GATT Server running. But maybe someone had success with this setup. 

The two GATT server will get as input the same data from the BLE sensor but broadcast different BLE profiles 

Bluez version: 5.50 
All Bluetooth dongle have different MAC addresses. 

I'm currently working on a project where I want to achieve the following setup: 

           +---------+
           |         |
           | BLE     |
           | Sensor  |
           | Server  |
           |         |
           +-----+---+
                 |
                 |
                 |
            +----+-----+
            |USB dongle|
            |BLE       |
            |Client    |
            |          |
      +-----+----------+---------+
      |    Raspberry             |
      |    pi                    |
      |                          |
      +--------------------------+
      | USB dongle|   |USB dongle|
      | BLE       |   |BLE       |
      | SerVer    |   |SerVer    |
      +-----+-----+   +------+---+
            |                |
    +-------+------+    +----+---------+
    |iOS device/   |    |iOS device/   |
    |Android device|    |Android device|
    |BLE client    |    |BLE client    |
    +--------------+    +--------------+

has someone already tried this sort of setup ?

**Comment by Vudentz** [comment]
GATT server is mandatory either way, also note that devices can assume multiple roles without a problem, so being a client and server at same times is not problem and you could in theory do connect to multiple phones while connected a sensor using a single  adapter if that allows to advertise/scan while connected.
