### ISSUE TITLE
Could SetDiscoveryFilter match UUID _or_ pattern?

### ISSUE THREAD

**Issue by abqjln** [bluez/bluez#982]
My central works with connectable servers with UUIDS, but also needs to discover beacons without UUIDs and only names/addresses. 

It seems the UUID filtering and pattern filtering in SetDiscoveryFilter does not "or" the results. Pattern and UUID filtering work independently if the other one is NULL. However it appears that If UUID is specified, it does not find items "pattern", without matching UUID.

It would be greatly preferable to have bluez do the filtering, but as of now I need to open it up completely (NULL, NULL) and filter later.

Am I doing something wrong? Thank you.
 
bluetoothctl: 5.78
RPi 4
Raspbian GNU/Linux 12 (bookworm)
Linux 6.6.51+rpt-rpi-v8
arm64

**Comment by Vudentz** [comment]
> My central works with connectable servers with UUIDS, but also needs to discover beacons without UUIDs and only names/addresses.
> 
> It seems the UUID filtering and pattern filtering in SetDiscoveryFilter does not "or" the results. Pattern and UUID filtering work independently if the other one is NULL. However it appears that If UUID is specified, it does not find items "pattern", without matching UUID.
> 
> It would be greatly preferable to have bluez do the filtering, but as of now I need to open it up completely (NULL, NULL) and filter later.
> 
> Am I doing something wrong? Thank you.
> 
> bluetoothctl: 5.78 RPi 4 Raspbian GNU/Linux 12 (bookworm) Linux 6.6.51+rpt-rpi-v8 arm64

Yeah, unfortunately this is the result of the limitation that the kernel only filters by UUID so it doesn't know the daemon is also implements filtering by address as well, so in order to fix this we will probably need to do the whole filtering at bluetoothd and perhaps add another field to enable logical AND/OR.

**Comment by abqjln** [comment]
OK, thanks. Workaround for now is what I have been doing--using SetDiscoveryFilter with NULL, NULL (aka not using it) and filtering in the application.
