### ISSUE TITLE
List of bluetooth adapters

### ISSUE THREAD

**Issue by gitchander** [bluez/bluez#987]
How I can get list of available bluetooth adapters with bluez (without using hciconfig)?

**Comment by Vudentz** [comment]
[bluetoothctl](https://github.com/bluez/bluez/blob/master/client/bluetoothctl.rst)> [list](https://github.com/bluez/bluez/blob/master/client/bluetoothctl.rst#list)

**Comment by gitchander** [comment]
bluetoothctl does not return more detailed parameters (adapter id: hci0).
