### ISSUE TITLE
What are the default values ​​of window and interval in le scanning mode?

### ISSUE THREAD

**Issue by eiSouthBoy** [bluez/bluez#992]
Hi
I have a problem. When I run the bluetoothctl application and execute the command ‘scan le’ in the window, the controller is in le scanning mode and everything is normal. But I want to know what are the default values ​​of the **interval** and **window** of le scanning? And how can I modify these two values?

Test environment：
OS: ubuntu 24.04
bluez version: 5.72

Looking forward to your reply.

**Comment by Vudentz** [comment]
> Hi I have a problem. When I run the bluetoothctl application and execute the command ‘scan le’ in the window, the controller is in le scanning mode and everything is normal. But I want to know what are the default values ​​of the **interval** and **window** of le scanning? And how can I modify these two values?
> 
> Test environment： OS: ubuntu 24.04 bluez version: 5.72
> 
> Looking forward to your reply.

Run btmon and bluetoothctl> scan le:

```
< HCI Command: LE Set Extended Scan Parameters (0x08|0x0041) plen 13                                                 #5 [hci0] 15:30:03.889810
        Own address type: Random (0x01)
        Filter policy: Accept all advertisement (0x00)
        PHYs: 0x05
        Entry 0: LE 1M
          Type: Active (0x01)
          Interval: 11.250 msec (0x0012)
          Window: 11.250 msec (0x0012)
        Entry 1: LE Coded
          Type: Active (0x01)
          Interval: 33.750 msec (0x0036)
          Window: 33.750 msec (0x0036)
```

These values comes from the spec and are set by the kernel (7c2cc5b1db509fb6e4a20c182cfbaf94255e4a7c):

`BLUETOOTH CORE SPECIFICATION Version 5.4 | Vol 3, Part C page 1375`
