### ISSUE TITLE
Excuse me, why can't my code below send data to the client correctly, and the client can't receive the data?

### ISSUE THREAD

**Issue by xtc002007** [bluez/bluez#997]
Excuse me, why can't my code below send data to the client correctly, and the client can't receive the data?

static gboolean chr_get_value(const GDBusPropertyTable *property,
					DBusMessageIter *iter, void *user_data)
{
	struct characteristic *chr = static_cast<struct characteristic*>(user_data);

	printf("Characteristic(%s): Get(\"Value\")\n", chr->uuid);
	
	print_characteristic_value(static_cast<struct characteristic*>(chr));

	// 读取 characteristic 的值并返回给客户端
    if (!chr_read(chr, iter)) {
        return FALSE;
    }

    // 获取客户端的 characteristic 的 path
    const char *client_chr_path = chr->path;
    printf("Client characteristic path: %s\n", client_chr_path);

	const char* response = "{\"code\":0, \"msg\", \"successful\"}"; 
	uint8_t* value = (uint8_t*)response;
	int len = strlen(response);
	chr_write(chr, value, len);

    return TRUE;
}

**Comment by Vudentz** [comment]
> Excuse me, why can't my code below send data to the client correctly, and the client can't receive the data?
> 
> static gboolean chr_get_value(const GDBusPropertyTable *property, DBusMessageIter *iter, void *user_data) { struct characteristic _chr = static_cast<struct characteristic_>(user_data);
> 
> ```
> printf("Characteristic(%s): Get(\"Value\")\n", chr->uuid);
> 
> print_characteristic_value(static_cast<struct characteristic*>(chr));
> 
> // 读取 characteristic 的值并返回给客户端
> if (!chr_read(chr, iter)) {
>     return FALSE;
> }
> 
> // 获取客户端的 characteristic 的 path
> const char *client_chr_path = chr->path;
> printf("Client characteristic path: %s\n", client_chr_path);
> 
> const char* response = "{\"code\":0, \"msg\", \"successful\"}"; 
> uint8_t* value = (uint8_t*)response;
> int len = strlen(response);
> chr_write(chr, value, len);
> 
> return TRUE;
> ```
> 
> }

Don't think this classify as an issue if you just want help debugging some code, anyway there are examples in the tree to access GATT attributes for example:

[client] https://github.com/bluez/bluez/blob/master/client/gatt.c#L2272
[server] https://github.com/bluez/bluez/blob/master/client/gatt.c#L2291

Those are available as part of [bluetoothctl-gatt(1)](https://github.com/bluez/bluez/blob/master/client/bluetoothctl-gatt.rst)
